-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.11.2-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.4.0.6659
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for vorpcore_1
CREATE DATABASE IF NOT EXISTS `vorpcore_1` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci */;
USE `vorpcore_1`;

-- Dumping structure for table vorpcore_1.banks
CREATE TABLE IF NOT EXISTS `banks` (
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table vorpcore_1.banks: ~4 rows (approximately)
INSERT INTO `banks` (`name`) VALUES
	('Blackwater'),
	('Rhodes'),
	('SaintDenis'),
	('Valentine');

-- Dumping structure for table vorpcore_1.bank_users
CREATE TABLE IF NOT EXISTS `bank_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `identifier` varchar(50) NOT NULL,
  `charidentifier` int(11) NOT NULL,
  `money` double(22,2) DEFAULT 0.00,
  `gold` double(22,2) DEFAULT 0.00,
  `items` longtext DEFAULT '[]',
  `invspace` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  CONSTRAINT `bank` FOREIGN KEY (`name`) REFERENCES `banks` (`name`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table vorpcore_1.bank_users: ~7 rows (approximately)
INSERT INTO `bank_users` (`id`, `name`, `identifier`, `charidentifier`, `money`, `gold`, `items`, `invspace`) VALUES
	(1, 'SaintDenis', 'steam:1100001060850f9', 1, 100.00, 0.00, '[]', 10),
	(2, 'SaintDenis', 'steam:110000114e4c691', 9, 0.00, 0.00, '[]', 10),
	(3, 'Rhodes', 'steam:1100001060850f9', 1, 100.00, 0.00, '[]', 10),
	(4, 'Blackwater', 'steam:110000114e4c691', 9, 10.00, 0.00, '[]', 10),
	(5, 'Blackwater', 'steam:1100001060850f9', 1, 100.00, 0.00, '[]', 10),
	(6, 'Valentine', 'steam:110000114e4c691', 9, 0.00, 0.00, '[]', 10),
	(7, 'Valentine', 'steam:1100001060850f9', 1, 0.00, 0.00, '[]', 10);

-- Dumping structure for table vorpcore_1.banneds
CREATE TABLE IF NOT EXISTS `banneds` (
  `b_id` int(11) NOT NULL AUTO_INCREMENT,
  `b_steam` varchar(100) NOT NULL,
  `b_license` varchar(255) DEFAULT NULL,
  `b_discord` varchar(100) DEFAULT NULL,
  `b_reason` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `b_banned` varchar(100) NOT NULL,
  `b_unban` varchar(100) NOT NULL,
  `b_permanent` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`b_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table vorpcore_1.banneds: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.bills
CREATE TABLE IF NOT EXISTS `bills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job` longtext DEFAULT NULL,
  `playername` longtext DEFAULT NULL,
  `identifier` varchar(50) DEFAULT NULL,
  `charidentifier` int(11) DEFAULT NULL,
  `issuer` longtext DEFAULT NULL,
  `amount` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table vorpcore_1.bills: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.characters
CREATE TABLE IF NOT EXISTS `characters` (
  `identifier` varchar(50) NOT NULL DEFAULT '',
  `steamname` varchar(50) NOT NULL DEFAULT '',
  `charidentifier` int(11) NOT NULL AUTO_INCREMENT,
  `group` varchar(10) DEFAULT 'user',
  `money` double(11,2) DEFAULT 0.00,
  `gold` double(11,2) DEFAULT 0.00,
  `rol` double(11,2) NOT NULL DEFAULT 0.00,
  `xp` int(11) DEFAULT 0,
  `healthouter` int(4) DEFAULT 500,
  `healthinner` int(4) DEFAULT 100,
  `staminaouter` int(4) DEFAULT 100,
  `staminainner` int(4) DEFAULT 100,
  `hours` float NOT NULL DEFAULT 0,
  `LastLogin` date DEFAULT NULL,
  `inventory` longtext DEFAULT NULL,
  `job` varchar(50) DEFAULT 'unemployed',
  `status` varchar(140) DEFAULT '{}',
  `meta` varchar(255) NOT NULL DEFAULT '{}',
  `firstname` varchar(50) DEFAULT ' ',
  `lastname` varchar(50) DEFAULT ' ',
  `skinPlayer` longtext DEFAULT NULL,
  `compPlayer` longtext DEFAULT NULL,
  `jobgrade` int(11) DEFAULT 0,
  `coords` longtext DEFAULT NULL,
  `isdead` tinyint(1) DEFAULT 0,
  `clanid` int(11) DEFAULT 0,
  `trust` int(11) DEFAULT 0,
  `supporter` int(11) DEFAULT 0,
  `walk` varchar(50) DEFAULT 'noanim',
  `crafting` longtext DEFAULT '{"medical":0,"blacksmith":0,"basic":0,"survival":0,"brewing":0,"food":0}',
  `info` longtext DEFAULT '{}',
  `gunsmith` double(11,2) DEFAULT 0.00,
  `ammo` longtext DEFAULT '{}',
  `clan` int(11) DEFAULT 0,
  `discordid` varchar(255) DEFAULT '0',
  `lastjoined` longtext DEFAULT '[]',
  `motel` varchar(255) DEFAULT '0',
  `moonshineenty` longtext DEFAULT '{}',
  UNIQUE KEY `identifier_charidentifier` (`identifier`,`charidentifier`) USING BTREE,
  KEY `charidentifier` (`charidentifier`) USING BTREE,
  KEY `clanid` (`clanid`),
  KEY `crafting` (`crafting`(768)),
  KEY `compPlayer` (`compPlayer`(768)),
  KEY `info` (`info`(768)),
  KEY `inventory` (`inventory`(768)),
  KEY `coords` (`coords`(768)),
  KEY `money` (`money`),
  KEY `meta` (`meta`),
  KEY `steamname` (`steamname`),
  KEY `ammo` (`ammo`(768)),
  CONSTRAINT `FK_characters_users` FOREIGN KEY (`identifier`) REFERENCES `users` (`identifier`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- Dumping structure for table vorpcore_1.character_inventories
CREATE TABLE IF NOT EXISTS `character_inventories` (
  `character_id` int(11) DEFAULT NULL,
  `inventory_type` varchar(100) NOT NULL DEFAULT 'default',
  `item_crafted_id` int(11) NOT NULL,
  `amount` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  KEY `character_inventory_idx` (`character_id`,`inventory_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping structure for table vorpcore_1.communityservice
CREATE TABLE IF NOT EXISTS `communityservice` (
  `identifier` varchar(100) NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL DEFAULT '0',
  `characterid` varchar(5) NOT NULL DEFAULT '0',
  `communityservice` varchar(100) NOT NULL DEFAULT '0',
  `servicecount` varchar(100) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table vorpcore_1.communityservice: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.companions
CREATE TABLE IF NOT EXISTS `companions` (
  `identifier` varchar(40) NOT NULL,
  `charidentifier` int(11) NOT NULL DEFAULT 0,
  `dog` varchar(255) NOT NULL,
  `skin` int(11) NOT NULL DEFAULT 0,
  `xp` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- Dumping structure for table vorpcore_1.doors
CREATE TABLE IF NOT EXISTS `doors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `doorinfo` longtext NOT NULL DEFAULT '[]',
  `job` longtext NOT NULL DEFAULT '[]',
  `item` longtext NOT NULL,
  `break` int(11) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table vorpcore_1.doors: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.herbalists
CREATE TABLE IF NOT EXISTS `herbalists` (
  `identifier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `charidentifier` int(11) NOT NULL,
  `location` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`identifier`) USING BTREE,
  UNIQUE KEY `identifier_charidentifier` (`identifier`,`charidentifier`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table vorpcore_1.herbalists: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.horse_complements
CREATE TABLE IF NOT EXISTS `horse_complements` (
  `identifier` varchar(50) NOT NULL,
  `charidentifier` int(11) NOT NULL,
  `complements` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  UNIQUE KEY `identifier` (`identifier`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table vorpcore_1.horse_complements: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.housing
CREATE TABLE IF NOT EXISTS `housing` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(255) DEFAULT NULL,
  `charidentifier` int(11) NOT NULL,
  `inventory` longtext DEFAULT NULL,
  `furniture` longtext DEFAULT NULL,
  `open` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=34307 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping structure for table vorpcore_1.items
CREATE TABLE IF NOT EXISTS `items` (
  `item` varchar(50) NOT NULL,
  `label` varchar(50) NOT NULL,
  `limit` int(11) NOT NULL DEFAULT 1,
  `can_remove` tinyint(1) NOT NULL DEFAULT 1,
  `type` varchar(50) DEFAULT NULL,
  `usable` tinyint(1) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '{}' CHECK (json_valid(`metadata`)),
  `desc` varchar(5550) NOT NULL DEFAULT 'nice item',
  PRIMARY KEY (`item`) USING BTREE,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table vorpcore_1.items: ~788 rows (approximately)
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `id`, `metadata`, `desc`) VALUES
	('acid', 'Acid', 10, 1, 'item_standard', 1, 1, '{}', 'nice item'),
	('Agarita', 'Agarita', 10, 1, 'item_standard', 1, 2, '{}', 'Herb used by Natives for crafting'),
	('Agarita_Seed', 'Agarita Seed', 10, 1, 'item_standard', 1, 3, '{}', 'Used to plant Agarita'),
	('Alaskan_Ginseng', 'Alaskan Ginseng', 10, 1, 'item_standard', 1, 4, '{}', 'Herb used for crafting'),
	('Alaskan_Ginseng_Seed', 'Alaskan Ginseng Seed', 10, 1, 'item_standard', 1, 5, '{}', 'Used to plant Alaskan Ginseng'),
	('alcohol', 'Alcohol', 10, 1, 'item_standard', 1, 6, '{}', 'Used in crafting of medicated bandages'),
	('aligatormeat', 'Alligator Meat', 20, 1, 'item_standard', 1, 568, '{}', 'Meat from Aligator used in crafting'),
	('aligators', 'Alligator pelt', 20, 1, 'item_standard', 1, 544, '{}', 'Cane be sold or crafted'),
	('aligatorto', 'Alligator tooth', 20, 1, 'item_standard', 1, 543, '{}', 'Can be sold or crafted'),
	('American_Ginseng', 'American Ginseng', 10, 1, 'item_standard', 1, 7, '{}', 'Herb used for crafting'),
	('American_Ginseng_Seed', 'American Ginseng Seed', 10, 1, 'item_standard', 1, 8, '{}', 'Used to plant American Ginseng'),
	('American_Tobacco', 'American Tobacco', 20, 1, 'item_standard', 1, 920, '{}', 'Used in crafting'),
	('American_Tobacco_Seed', 'American Tobacco Seeds', 20, 1, 'item_standard', 1, 921, '{}', 'Used to plant American Tobacco'),
	('ammoarrowdynamite', 'Arrow Dynamite', 10, 1, 'item_standard', 1, 10, '{}', 'Ammunition for Bow'),
	('ammoarrowfire', 'Arrow Fire', 10, 1, 'item_standard', 1, 11, '{}', 'Ammunition for Bow'),
	('ammoarrowimproved', 'Arrow Improved', 10, 1, 'item_standard', 1, 12, '{}', 'Ammunition for Bow'),
	('ammoarrownormal', 'Arrow Normal', 10, 1, 'item_standard', 1, 9, '{}', 'Ammunition for Bow'),
	('ammoarrowpoison', 'Arrow Poison', 10, 1, 'item_standard', 1, 13, '{}', 'Ammunition for Bow'),
	('ammoarrowsmallgame', 'Arrow Small Game', 10, 1, 'item_standard', 1, 14, '{}', 'Ammunition for Bow'),
	('ammobolahawk', 'Bola Ammo Hawk', 10, 1, 'item_standard', 1, 15, '{}', 'nice item'),
	('ammobolainterwired', 'Bola Ammo Interwired', 10, 1, 'item_standard', 1, 16, '{}', 'nice item'),
	('ammobolaironspiked', 'Bola Ammo Ironspiked', 10, 1, 'item_standard', 1, 17, '{}', 'nice item'),
	('ammobolla', 'Bolla Ammo', 10, 1, 'item_standard', 1, 18, '{}', 'nice item'),
	('ammodynamite', 'Dynamite Ammo', 10, 1, 'item_standard', 1, 19, '{}', 'Created by Alfred Nobel as alternative to gunpowder.'),
	('ammoelephant', 'Elephant Rifle Ammo', 10, 1, 'item_standard', 1, 20, '{}', 'Ammunition for Elephant Rifle'),
	('ammoknives', 'Knives Ammo', 10, 1, 'item_standard', 1, 21, '{}', 'Throwing knives'),
	('ammomolotov', 'Molotov Ammo', 10, 1, 'item_standard', 1, 22, '{}', 'You know what this is for...bad bad person.'),
	('ammopistolexplosive', 'Pistol Ammo Explosive', 10, 1, 'item_standard', 1, 23, '{}', 'Explosive rounds for pistol'),
	('ammopistolexpress', 'Pistol Ammo Express', 10, 1, 'item_standard', 1, 24, '{}', 'Express rounds for pistol'),
	('ammopistolnormal', 'Pistol Ammo Normal', 10, 1, 'item_standard', 1, 25, '{}', 'Normal pistol rounds'),
	('ammopistolsplitpoint', 'Pistol Ammo Splitpoint', 10, 1, 'item_standard', 1, 26, '{}', 'Split point rounds for pistol'),
	('ammopistolvelocity', 'Pistol Ammo Velocity', 10, 1, 'item_standard', 1, 27, '{}', 'High velocity rounds for pistol'),
	('ammopoisonbottle', 'Poison Bottle Ammo', 10, 1, 'item_standard', 1, 28, '{}', 'nice item'),
	('ammorepeaterexplosive', 'Repeater Ammo Explosive', 10, 1, 'item_standard', 1, 29, '{}', 'Explosive rounds for repeater'),
	('ammorepeaterexpress', 'Repeater Ammo Express', 10, 1, 'item_standard', 1, 30, '{}', 'Express rounds for repeater'),
	('ammorepeaternormal', 'Repeater Ammo Normal', 10, 1, 'item_standard', 1, 31, '{}', 'Normal rounds for repeater'),
	('ammorepeatersplitpoint', 'Repeater Ammo Splitpoint', 10, 1, 'item_standard', 1, 32, '{}', 'Splitpoint rounds for repeater'),
	('ammorepeatervelocity', 'Repeater Ammo Velocity', 10, 1, 'item_standard', 1, 33, '{}', 'High velocity rounds for repeater'),
	('ammorevolverexplosive', 'Revolver Ammo Explosive', 10, 1, 'item_standard', 1, 34, '{}', 'Explosive rounds for revolver'),
	('ammorevolverexpress', 'Revolver Ammo Express', 10, 1, 'item_standard', 1, 35, '{}', 'Express rounds for revolver'),
	('ammorevolvernormal', 'Revolver Ammo Normal', 10, 1, 'item_standard', 1, 36, '{}', 'Normal rounds for revolver'),
	('ammorevolversplitpoint', 'Revolver Ammo Splitpoint', 10, 1, 'item_standard', 1, 37, '{}', 'Split point rounds for revolver'),
	('ammorevolvervelocity', 'Revolver Ammo Velocity', 10, 1, 'item_standard', 1, 38, '{}', 'High velocity rounds for revolver'),
	('ammorifleexplosive', 'Rifle Ammo Explosive', 10, 1, 'item_standard', 1, 39, '{}', 'Explosive rounds for rifle'),
	('ammorifleexpress', 'Rifle Ammo Express', 10, 1, 'item_standard', 1, 40, '{}', 'Express rounds for rifle'),
	('ammoriflenormal', 'Rifle Ammo Normal', 10, 1, 'item_standard', 1, 41, '{}', 'Normal rounds for rifle'),
	('ammoriflesplitpoint', 'Rifle Ammo Splitpoint', 10, 1, 'item_standard', 1, 42, '{}', 'Split point rounds for rifle'),
	('ammoriflevelocity', 'Rifle Ammo Velocity', 10, 1, 'item_standard', 1, 43, '{}', 'High velocity rounds for rifle'),
	('ammoshotgunexplosive', 'Shotgun Ammo Explosive', 10, 1, 'item_standard', 1, 44, '{}', 'Explosive rounds for shotgun'),
	('ammoshotgunincendiary', 'Shotgun Ammo Incendiary', 10, 1, 'item_standard', 1, 45, '{}', 'Incendiary rounds for shotgun'),
	('ammoshotgunnormal', 'Shotgun Ammo Normal', 10, 1, 'item_standard', 1, 46, '{}', 'Normal rounds for shotgun'),
	('ammoshotgunslug', 'Shotgun Ammo Slug', 10, 1, 'item_standard', 1, 47, '{}', 'Slugs for shotgun'),
	('ammotomahawk', 'Tonmahawk Ammo', 10, 1, 'item_standard', 1, 48, '{}', 'Why are you running?'),
	('ammovarmint', 'Varmint Ammo', 10, 1, 'item_standard', 1, 49, '{}', 'Ammunition for varmint rifle'),
	('ammovarminttranq', 'Varmint Tranquilizer Ammo', 10, 1, 'item_standard', 1, 50, '{}', 'Tranuilizers for varmint rifle'),
	('ammovoldynamite', 'Volatile Dynamite Ammo', 10, 1, 'item_standard', 1, 51, '{}', 'Feeling frisky?'),
	('ammovolmolotov', 'Volatile Molotov Ammo', 10, 1, 'item_standard', 1, 52, '{}', 'This...is a bad idea'),
	('antipoison', 'Antipoison', 20, 1, 'item_standard', 1, 53, '{}', 'nice item'),
	('antipoison2', 'Anti Snake Poison', 20, 1, 'item_standard', 1, 617, '{}', 'Next time watch your step'),
	('apple', 'Apple for Horse', 20, 1, 'item_standard', 1, 54, '{}', 'Apple for horses'),
	('applebarrel', 'Apple Barrel', 20, 1, 'item_standard', 1, 762, '{}', 'nice item'),
	('applebasket', 'Apple Basket', 20, 1, 'item_standard', 1, 763, '{}', 'nice item'),
	('appleCrumbMash', 'Minty Berry Mash', 10, 1, 'item_standard', 1, 55, '{}', 'Used in crafting'),
	('appleCrumbMoonshine', 'Minty Berry Moonshine', 10, 1, 'item_standard', 1, 56, '{}', 'Feeling frisky?'),
	('apple_barrel', 'Apple Barrel', 20, 1, 'item_standard', 1, 634, '{}', 'nice item'),
	('apple_basket', 'Apple Basket', 20, 1, 'item_standard', 1, 635, '{}', 'nice item'),
	('apple_pie_oml', 'Larry\'s Apple Pie', 20, 1, 'item_standard', 1, 916, '{}', 'Old Man Larry\'s Famous Apple Pie'),
	('Apple_Seed', 'Apple Seed', 10, 1, 'item_standard', 1, 727, '{}', 'Used for crafting'),
	('armadilloc', 'Armadillo claws', 20, 1, 'item_standard', 1, 449, '{}', 'Can be sold or crafted'),
	('armadillos', 'Armadillo pelt', 20, 1, 'item_standard', 1, 448, '{}', 'Can be sold or crafted'),
	('asnakes', 'Copperhead Snake pelt', 20, 1, 'item_standard', 1, 487, '{}', 'Can be sold or crafted'),
	('a_c_fishbluegil_01_ms', 'Medium Bluegil', 10, 1, 'item_standard', 0, 57, '{}', 'Can be sold or crafted'),
	('a_c_fishbluegil_01_sm', 'Small Bluegil', 5, 1, 'item_standard', 0, 58, '{}', 'Can be sold or crafted'),
	('a_c_fishbullheadcat_01_ms', 'Medium Bullhead', 10, 1, 'item_standard', 0, 59, '{}', 'Can be sold or crafted'),
	('a_c_fishbullheadcat_01_sm', 'Small Bullhead', 5, 1, 'item_standard', 0, 60, '{}', 'Can be sold or crafted'),
	('a_c_fishchainpickerel_01_ms', 'Medium Pickerel', 10, 1, 'item_standard', 0, 61, '{}', 'Can be sold or crafted'),
	('a_c_fishchainpickerel_01_sm', 'Small Pickerel', 5, 1, 'item_standard', 0, 62, '{}', 'Can be sold or crafted'),
	('a_c_fishchannelcatfish_01_lg', 'Channel Catfish (Large)', 10, 1, 'item_standard', 0, 953, '{}', 'Can be sold or crafted'),
	('a_c_fishchannelcatfish_01_xl', 'Channel Catfish (Extra Large)', 10, 1, 'item_standard', 0, 954, '{}', 'Can be sold or crafted'),
	('a_c_fishlakesturgeon_01_lg', 'Lake Sturgeon (Large)', 10, 1, 'item_standard', 0, 955, '{}', 'Can be sold or crafted'),
	('a_c_fishlargemouthbass_01_lg', 'Large Mouth Bass (Large)', 10, 1, 'item_standard', 0, 956, '{}', 'Can be sold or crafted'),
	('a_c_fishlargemouthbass_01_ms', 'Lardgemouth Bass', 10, 1, 'item_standard', 0, 63, '{}', 'Can be sold or crafted'),
	('a_c_fishlongnosegar_01_lg', 'Long Nose Gar (Large)', 10, 1, 'item_standard', 0, 957, '{}', 'Can be sold or crafted'),
	('a_c_fishmuskie_01_lg', 'Muskie (Large)', 10, 1, 'item_standard', 0, 958, '{}', 'Can be sold or crafted'),
	('a_c_fishnorthernpike_01_lg', 'Northern Pike (Large)', 10, 1, 'item_standard', 0, 959, '{}', 'Can be sold or crafted'),
	('a_c_fishperch_01_ms', 'Medium Perch', 10, 1, 'item_standard', 0, 64, '{}', 'Can be sold or crafted'),
	('a_c_fishperch_01_sm', 'Small Perch', 5, 1, 'item_standard', 0, 65, '{}', 'Can be sold or crafted'),
	('a_c_fishrainbowtrout_01_lg', 'Rainbow Trout (Large)', 10, 1, 'item_standard', 0, 960, '{}', 'Can be sold or crafted'),
	('a_c_fishrainbowtrout_01_ms', 'Rainbow Trout', 10, 1, 'item_standard', 0, 66, '{}', 'Can be sold or crafted'),
	('a_c_fishredfinpickerel_01_ms', 'Medium Redfin Pickerel', 10, 1, 'item_standard', 0, 67, '{}', 'Can be sold or crafted'),
	('a_c_fishredfinpickerel_01_sm', 'Small Redfin Pickerel', 5, 1, 'item_standard', 0, 68, '{}', 'Can be sold or crafted'),
	('a_c_fishrockbass_01_ms', 'Medium Rockbass', 10, 1, 'item_standard', 0, 69, '{}', 'Can be sold or crafted'),
	('a_c_fishrockbass_01_sm', 'Small Rockbass', 5, 1, 'item_standard', 0, 70, '{}', 'Can be sold or crafted'),
	('a_c_fishsalmonsockeye_01_lg', 'Salmon Sockeye (Large)', 10, 1, 'item_standard', 0, 961, '{}', 'Can be sold or crafted'),
	('a_c_fishsalmonsockeye_01_ml', 'Salmon Sockeye (Medium-Large)', 10, 1, 'item_standard', 0, 962, '{}', 'Can be sold or crafted'),
	('a_c_fishsalmonsockeye_01_ms', 'Sockeye Salmon', 10, 1, 'item_standard', 0, 71, '{}', 'Can be sold or crafted'),
	('a_c_fishsmallmouthbass_01_lg', 'Small Mouth Bass (Large)', 10, 1, 'item_standard', 0, 963, '{}', 'Can be sold or crafted'),
	('a_c_fishsmallmouthbass_01_ms', 'Smallmouth Bass', 10, 1, 'item_standard', 0, 72, '{}', 'Can be sold or crafted'),
	('badgers', 'Badger skin', 20, 1, 'item_standard', 1, 491, '{}', 'Can be sold or crafted'),
	('bait', 'Bait', 20, 1, 'item_standard', 1, 73, '{}', 'For fishing'),
	('banana', 'Banana', 20, 1, 'item_standard', 1, 74, '{}', 'nice item'),
	('bandage', 'Bandage', 20, 1, 'item_standard', 1, 75, '{}', 'Got a booboo...this will help'),
	('bandage_med', 'Medicated Bandage', 10, 1, 'item_standard', 0, 987, '{}', 'For the big booboos'),
	('barrel', 'Barrel', 5, 1, 'item_standard', 1, 800, '{}', 'nice item'),
	('bat_c', 'Bat', 20, 1, 'item_standard', 1, 420, '{}', 'Can be sold'),
	('Bay_Bolete', 'Bay Bolete', 10, 1, 'item_standard', 1, 76, '{}', 'Used for cratting'),
	('Bay_Bolete_Seed', 'Bay Bolete Spores', 10, 1, 'item_standard', 1, 77, '{}', 'Spores for Bay Bolete'),
	('bbears', 'Black Bear skin', 20, 1, 'item_standard', 1, 452, '{}', 'Can be sold or crafted'),
	('bbirdb', 'Cormorant beak', 20, 1, 'item_standard', 1, 528, '{}', 'Can be sold or crafted'),
	('bbirdf', 'Cormorant feather', 20, 1, 'item_standard', 1, 527, '{}', 'Can be sold or crafted'),
	('bcandle', 'Bottle Candle', 20, 1, 'item_standard', 1, 663, '{}', 'nice item'),
	('bearbench', 'Bear Bench', 20, 1, 'item_standard', 1, 773, '{}', 'nice item'),
	('bearc', 'Bear claws', 20, 1, 'item_standard', 1, 450, '{}', 'Can be sold or crafted'),
	('beart', 'Bear tooth', 20, 1, 'item_standard', 1, 451, '{}', 'Can be sold or crafted'),
	('bear_bench', 'Bear Bench', 20, 1, 'item_standard', 1, 645, '{}', 'nice item'),
	('beavers', 'Beaver pelt', 20, 1, 'item_standard', 1, 541, '{}', 'Can be sold or crafted'),
	('beavertail', 'Beaver tail', 20, 1, 'item_standard', 1, 542, '{}', 'Can be sold'),
	('beef', 'Beef', 20, 1, 'item_standard', 1, 567, '{}', 'Can be sold or crafted'),
	('beefjerky', 'Beef Jerky', 20, 1, 'item_standard', 1, 78, '{}', 'For the long haul'),
	('beer', 'Beer', 10, 1, 'item_standard', 1, 79, '{}', 'Life is hard, huh? This will help...temporarily'),
	('beerbox', 'Beer Box', 20, 1, 'item_standard', 1, 586, '{}', 'nice item'),
	('bigchest', 'Big Chest', 1, 1, 'item_standard', 1, 658, '{}', 'nice item'),
	('biggame', 'Big Game Meat', 20, 1, 'item_standard', 1, 565, '{}', 'Can be sold or crafted'),
	('Big_Leather', 'Big Leather', 10, 1, 'item_standard', 1, 80, '{}', 'nice item'),
	('bird', 'Bird Meat', 20, 1, 'item_standard', 1, 569, '{}', 'Can be sold or crafted'),
	('bisonhorn', 'Bison horn', 20, 1, 'item_standard', 1, 461, '{}', 'Can be sold or crafted'),
	('bisons', 'Bison pelt', 20, 1, 'item_standard', 1, 462, '{}', 'Can be sold or crafted'),
	('Bitter_Weed', 'Bitter Weed', 10, 1, 'item_standard', 1, 81, '{}', 'Herb used for crafting'),
	('Bitter_Weed_Seed', 'Bitter Weed Seed', 10, 1, 'item_standard', 1, 82, '{}', 'Used to plant Bitter Weed'),
	('blackberryale', 'Black Berry Ale', 10, 1, 'item_standard', 1, 83, '{}', 'Nice ale to cool down on a hot day'),
	('Black_Berry', 'Black Berry', 10, 1, 'item_standard', 1, 84, '{}', 'Can be consumed or crafted'),
	('Black_Berry_Seed', 'Black Berry Seed', 10, 1, 'item_standard', 1, 85, '{}', 'Used for farming'),
	('Black_Currant', 'Black Currant', 10, 1, 'item_standard', 1, 86, '{}', 'Can be consumed or crafted'),
	('Black_Currant_Seed', 'Black Currant Seed', 10, 1, 'item_standard', 1, 87, '{}', 'Used for farming'),
	('blanketbox', 'Blanket Box', 20, 1, 'item_standard', 1, 760, '{}', 'nice item'),
	('blanket_box', 'Blanket Box', 20, 1, 'item_standard', 1, 632, '{}', 'nice item'),
	('blindfold', 'Blindfold', 10, 1, 'item_standard', 1, 913, '{}', 'They don;t need to see'),
	('Blood_Flower', 'Blood Flower', 10, 1, 'item_standard', 1, 88, '{}', 'Used for craftig'),
	('Blood_Flower_Seed', 'Blood Flower Seed', 10, 1, 'item_standard', 1, 89, '{}', 'Used for farming'),
	('blueberry', 'Blueberry', 10, 1, 'item_standard', 1, 90, '{}', 'Can be consumed or crafted'),
	('bluejay_c', 'Blue jay', 20, 1, 'item_standard', 1, 421, '{}', 'Can be sold'),
	('bmdresser', 'brown mirror dresser', 20, 1, 'item_standard', 1, 652, '{}', 'Home furnishing'),
	('boarmusk', 'Boar tusk', 20, 1, 'item_standard', 1, 456, '{}', 'Can be sold or crafted'),
	('boars', 'Boar pelt', 20, 1, 'item_standard', 1, 457, '{}', 'Can be sold or crafted'),
	('boaskin', 'Boa Snake pelt', 20, 1, 'item_standard', 1, 486, '{}', 'Can be sold or crafted'),
	('boiledegg', 'Boiled Egg', 10, 1, 'item_standard', 1, 91, '{}', 'Can be consumed'),
	('boobyb', 'Red-footed booby beak', 20, 1, 'item_standard', 1, 501, '{}', 'Can be sold or crafted'),
	('boobyf', 'Red-footed booby feather', 20, 1, 'item_standard', 1, 500, '{}', 'Can be sold or crafted'),
	('book', 'Book', 5, 1, 'item_standard', 1, 92, '{}', 'nice item'),
	('Boost_For_Horse', 'Horse Stamina Boost', 20, 1, 'item_standard', 1, 993, '{}', 'Gotta go FAST!!!'),
	('bountylicns', 'Bounty Hunter License', 10, 1, 'item_standard', 1, 93, '{}', 'Required for bounty hunting'),
	('bouquet', 'Bouquet', 1, 1, 'item_standard', 1, 342, '{}', 'nice item'),
	('bparrotb', 'Parrot beak', 20, 1, 'item_standard', 1, 522, '{}', 'Can be sold or crafted'),
	('bparrotf', 'Parrot feather', 20, 1, 'item_standard', 1, 521, '{}', 'Can be sold or crafted'),
	('bread', 'Bread', 10, 1, 'item_standard', 1, 915, '{}', 'Can be consumed'),
	('buckantler', 'Buck Antlers', 20, 1, 'item_standard', 1, 459, '{}', 'Can be sold or crafted'),
	('bucks', 'Buck skin', 20, 1, 'item_standard', 1, 460, '{}', 'Can be sold or crafted'),
	('bullhorn', 'Bull horn', 20, 1, 'item_standard', 1, 463, '{}', 'Can be sold or crafted'),
	('bulls', 'Bull pelt', 20, 1, 'item_standard', 1, 464, '{}', 'Can be sold or crafted'),
	('Bulrush', 'Bulrush', 10, 1, 'item_standard', 1, 94, '{}', 'Used for crafting'),
	('Bulrush_Seed', 'Bulrush Seed', 10, 1, 'item_standard', 1, 95, '{}', 'Used for farming'),
	('bunkbed', 'bunk bed', 20, 1, 'item_standard', 1, 665, '{}', 'Home furnishing'),
	('Burdock_Root', 'Burdock Root', 10, 1, 'item_standard', 1, 96, '{}', 'Used for crafting'),
	('Burdock_Root_Seed', 'Burdock Root Seed', 10, 1, 'item_standard', 1, 97, '{}', 'Used for farming'),
	('butchertable1', 'Small Butcher Table', 20, 1, 'item_standard', 1, 583, '{}', 'Home furnishing'),
	('butchertable2', 'Medium Butcher Table', 20, 1, 'item_standard', 1, 582, '{}', 'Home furnishing'),
	('butchertable3', 'Large Butcher Table', 20, 1, 'item_standard', 1, 581, '{}', 'Home furnishing'),
	('bwdresser', 'brown wood dresser', 20, 1, 'item_standard', 1, 651, '{}', 'Home furnishing'),
	('camera', 'Camera', 1, 1, 'item_standard', 1, 346, '{}', 'nice item'),
	('campfire', 'Campfire', 5, 1, 'item_standard', 1, 98, '{}', 'Used for crafting'),
	('candlea', 'Candle', 20, 1, 'item_standard', 1, 661, '{}', 'nice item'),
	('cane', 'Cane', 1, 1, 'item_standard', 1, 344, '{}', 'nice item'),
	('canteen', 'Canteen (Full)', 1, 1, 'item_standard', 1, 909, '{}', 'Holds water for drinking'),
	('canteenempty', 'Canteen (Empty)', 1, 1, 'item_standard', 1, 908, '{}', 'Holds water for drinking'),
	('canteen_25', 'Canteen (25%)', 1, 1, 'item_standard', 1, 912, '{}', 'Holds water for drinking'),
	('canteen_50', 'Canteen (50%)', 1, 1, 'item_standard', 1, 911, '{}', 'Holds water for drinking'),
	('canteen_75', 'Canteen (75%)', 1, 1, 'item_standard', 1, 910, '{}', 'Holds water for drinking'),
	('cardinal_c', 'Cardinal bird', 20, 1, 'item_standard', 1, 422, '{}', 'Can be sold'),
	('Cardinal_Flower', 'Cardinal Flower', 10, 1, 'item_standard', 1, 99, '{}', 'Used for crafting'),
	('Cardinal_Flower_Seed', 'Cardinal Flower Seed', 10, 1, 'item_standard', 1, 100, '{}', 'Used for farming'),
	('carrot', 'Carrot', 12, 1, 'item_standard', 1, 982, '{}', 'nice item'),
	('carrots', 'Carrot', 10, 1, 'item_standard', 1, 101, '{}', 'Can be consumed'),
	('carrot_wild', 'Wild Carrot', 10, 1, 'item_standard', 1, 319, '{}', 'Carrot for horses'),
	('carrot_wild_seed', 'Wild Carrot Seed', 10, 1, 'item_standard', 1, 320, '{}', 'Used for farming'),
	('cedarwaxwing_c', 'Cedar waxwing', 20, 1, 'item_standard', 1, 423, '{}', 'Can be sold'),
	('Chanterelles', 'Chanterelles', 10, 1, 'item_standard', 1, 102, '{}', 'Can be consumed or crafted'),
	('Chanterelles_Seed', 'Chanterelles Seed', 10, 1, 'item_standard', 1, 103, '{}', 'Used for farming'),
	('char', 'Char', 10, 1, 'item_standard', 0, 104, '{}', 'nice item'),
	('chestc', 'Chest C', 20, 1, 'item_standard', 1, 578, '{}', 'Home furnishing'),
	('chewingtobacco', 'Chewing Tobacco', 20, 1, 'item_standard', 1, 105, '{}', 'Can be consumed'),
	('chickenf', 'Chicken feather', 20, 1, 'item_standard', 1, 525, '{}', 'Can be sold or crafted'),
	('chickenheart', 'Chicken heart', 20, 1, 'item_standard', 1, 526, '{}', 'Can be sold or crafted'),
	('chipmunk_c', 'Chipmunk', 20, 1, 'item_standard', 1, 419, '{}', 'Can be sold'),
	('Choc_Daisy', 'Choc Daisy', 10, 1, 'item_standard', 1, 106, '{}', 'Used for crafting'),
	('Choc_Daisy_Seed', 'Choc Daisy Seed', 10, 1, 'item_standard', 1, 107, '{}', 'Used for farming'),
	('cigar', 'Cigar', 20, 1, 'item_standard', 1, 108, '{}', 'Can be consumed'),
	('cigarette', 'Cigarette', 20, 1, 'item_standard', 1, 109, '{}', 'Can be consumed'),
	('cigarettefilter', 'Cig Filter', 20, 1, 'item_standard', 1, 110, '{}', 'Used for crafting'),
	('cinematicket', 'Ticket', 2, 1, 'item_standard', 0, 351, '{}', 'What\'s playing?'),
	('clay', 'Clay', 20, 1, 'item_standard', 1, 111, '{}', 'Used for crafting'),
	('cleanser', 'Cleanser', 5, 1, 'item_standard', 1, 340, '{}', 'nice item'),
	('clothbench', 'Cloth Bench', 20, 1, 'item_standard', 1, 776, '{}', 'Home furnishing'),
	('clothesline', 'Clothes Line', 20, 1, 'item_standard', 1, 766, '{}', 'Home furnishing'),
	('clothes_line', 'Clothes Line', 20, 1, 'item_standard', 1, 638, '{}', 'Home furnishing'),
	('cloth_bench', 'Cloth Bench', 20, 1, 'item_standard', 1, 648, '{}', 'Home furnishing'),
	('coal', 'Coal', 20, 1, 'item_standard', 1, 112, '{}', 'Used for crafting'),
	('cockc', 'Rooster claws', 20, 1, 'item_standard', 1, 499, '{}', 'Can be sold or crafted'),
	('cockf', 'Rooster feather', 20, 1, 'item_standard', 1, 498, '{}', 'Can be sold or crafted'),
	('cocoa', 'Cocoa', 20, 1, 'item_standard', 1, 113, '{}', 'Used for crafting'),
	('cocoaseeds', 'Cocoa Seeds', 10, 1, 'item_standard', 1, 733, '{}', 'Used for farming'),
	('coffindecor', 'Coffin Decor', 20, 1, 'item_standard', 1, 629, '{}', 'nice item'),
	('condenser', 'Condenser', 5, 1, 'item_standard', 1, 816, '{}', 'nice item'),
	('condorb', 'Condor beak', 20, 1, 'item_standard', 1, 480, '{}', 'Can be sold or crafted'),
	('condorf', 'Condor feather', 20, 1, 'item_standard', 1, 479, '{}', 'Can be sold or crafted'),
	('consumable_apple', 'Apple', 10, 1, 'item_standard', 1, 917, '{}', 'Can be consumed'),
	('consumable_bluegil', 'Dried Bluegil', 10, 1, 'item_standard', 1, 114, '{}', 'Can be sold or crafted'),
	('consumable_breakfast', 'Breakfast', 5, 1, 'item_standard', 1, 115, '{}', 'Can be consumed'),
	('consumable_caramel', 'Caramel', 5, 1, 'item_standard', 1, 116, '{}', 'Can be consumed'),
	('consumable_chocolate', 'Chocolate Bar', 10, 1, 'item_standard', 1, 117, '{}', 'Can be consumed'),
	('consumable_coffee', 'Coffee', 5, 1, 'item_standard', 1, 118, '{}', 'Can be consumed'),
	('consumable_fruitsalad', 'Fruit Salad', 5, 1, 'item_standard', 1, 119, '{}', 'Can be consumed'),
	('consumable_game', 'Jerkied GameMeat', 10, 1, 'item_standard', 1, 120, '{}', 'Can be consumed'),
	('consumable_haycube', 'Haycube', 10, 1, 'item_standard', 1, 121, '{}', 'Feed for horse'),
	('consumable_herb_chanterelles', 'Chanterelles', 10, 1, 'item_standard', 1, 122, '{}', 'Can be consumed or crafted'),
	('consumable_herb_evergreen_huckleberry', 'Evergreen Huckleberry', 10, 1, 'item_standard', 1, 123, '{}', 'Can be consumed or crafted'),
	('consumable_herb_oregano', 'Oregano', 10, 1, 'item_standard', 1, 124, '{}', 'Used for crafting'),
	('consumable_herb_wintergreen_berry', 'Wintergreen Berry', 10, 1, 'item_standard', 1, 126, '{}', 'Used for crafting'),
	('consumable_kidneybeans_can', 'Kidney Beans', 5, 1, 'item_standard', 1, 127, '{}', 'Can be consumed'),
	('consumable_lock_breaker', 'Lock Breaker', 10, 1, 'item_standard', 1, 128, '{}', 'Used to break locks'),
	('consumable_meat_greavy', 'Meat Stew', 12, 1, 'item_standard', 1, 129, '{}', 'Can be consumed'),
	('consumable_medicine', 'Medicine', 10, 1, 'item_standard', 1, 130, '{}', 'For what ails ya'),
	('consumable_peach', 'Peach', 5, 1, 'item_standard', 1, 131, '{}', 'Can be consumed'),
	('consumable_pear', 'Pear', 10, 1, 'item_standard', 1, 132, '{}', 'Can be consumed'),
	('consumable_raspberrywater', 'Berry Water', 10, 1, 'item_standard', 1, 133, '{}', 'Can be consumed'),
	('consumable_salmon', 'Dried Salmon', 10, 1, 'item_standard', 1, 134, '{}', 'Can be consumed'),
	('consumable_salmon_can', 'Salmon Can', 10, 1, 'item_standard', 1, 135, '{}', 'Can be consumed'),
	('consumable_sugarcube', 'Sugar Cube', 10, 1, 'item_standard', 1, 919, '{}', 'Feed for horse'),
	('consumable_trout', 'Cooked Trout', 10, 1, 'item_standard', 1, 136, '{}', 'Can be consumed'),
	('consumable_veggies', 'Edible Veggies', 5, 1, 'item_standard', 1, 137, '{}', 'Can be consumed'),
	('cookedbluegil', 'Cooked Bluegil with Veggies', 5, 1, 'item_standard', 1, 138, '{}', 'Can be consumed'),
	('cooked_aligator_plain', 'Plain Cooked Alligator', 5, 1, 'item_standard', 1, 926, '{}', 'Can be consumed'),
	('cooked_biggame_plain', 'Plain Cooked Big Game', 5, 1, 'item_standard', 1, 925, '{}', 'Can be consumed'),
	('cooked_bird_plain', 'Plain Cooked Bird', 10, 1, 'item_standard', 1, 923, '{}', 'Can be consumed'),
	('cooked_game_plain', 'Plain Cooked Game', 10, 1, 'item_standard', 1, 922, '{}', 'Can be consumed'),
	('cooked_herptile_plain', 'Plain Cooked Reptile', 10, 1, 'item_standard', 1, 927, '{}', 'Can be consumed'),
	('cooked_mutton_plain', 'Plain Cooked Mutton', 10, 1, 'item_standard', 1, 928, '{}', 'Can be consumed'),
	('cooked_pork_plain', 'Plain Cooked Pork', 10, 1, 'item_standard', 1, 924, '{}', 'Can be consumed'),
	('cooked_stringy_plain', 'Plain Cooked Stringy Meat', 10, 1, 'item_standard', 1, 929, '{}', 'Can be consumed'),
	('cooked_venison_plain', 'Plain Cooked Venison', 5, 1, 'item_standard', 1, 938, '{}', 'Can be consumed'),
	('copper', 'Copper', 30, 1, 'item_standard', 1, 139, '{}', 'Used for crafting'),
	('corn', 'Corn', 10, 1, 'item_standard', 1, 140, '{}', 'Used for crafting'),
	('cornseed', 'Corn seed', 10, 1, 'item_standard', 1, 141, '{}', 'Used for farming'),
	('cougarf', 'Cougar tooth', 20, 1, 'item_standard', 1, 558, '{}', 'Can be sold or crafted'),
	('cougars', 'Cougar skin', 20, 1, 'item_standard', 1, 557, '{}', 'Can be sold or crafted'),
	('cougartaxi', 'Cougar Taxidermy', 20, 1, 'item_standard', 1, 771, '{}', 'Yeah, we heard the story'),
	('cougar_taxidermy', 'Cougar Taxidermy', 20, 1, 'item_standard', 1, 643, '{}', 'Yeah, we heard the story'),
	('cowh', 'Cow horn', 20, 1, 'item_standard', 1, 562, '{}', 'Can be sold or crafted'),
	('cows', 'Cow pelt', 20, 1, 'item_standard', 1, 561, '{}', 'Can be sold or crafted'),
	('coyotef', 'Coyote tooth', 20, 1, 'item_standard', 1, 560, '{}', 'Can be sold or crafted'),
	('coyotepelt', 'Coyote Pelt', 20, 1, 'item_standard', 1, 759, '{}', 'Can be sold or crafted'),
	('coyotes', 'Coyote skin', 20, 1, 'item_standard', 1, 559, '{}', 'Can be sold or crafted'),
	('coyotetaxi', 'Coyote Taxidermy', 20, 1, 'item_standard', 1, 768, '{}', 'Really, you are a terrible hunter if this is your prize'),
	('coyote_pelt', 'Coyote Pelt', 20, 1, 'item_standard', 1, 631, '{}', 'Can be sold or crafted'),
	('coyote_taxidermy', 'Coyote Taxidermy', 20, 1, 'item_standard', 1, 640, '{}', 'Really, you are a terrible hunter if this is your prize'),
	('crab_c', 'Crab', 20, 1, 'item_standard', 1, 425, '{}', 'Can be sold or crafted'),
	('craftingfire', 'Crafting Fire', 20, 1, 'item_standard', 1, 753, '{}', 'Used for crafting'),
	('crafting_fire', 'Crafting Fire', 20, 1, 'item_standard', 1, 625, '{}', 'Used for crafting'),
	('crawfish_c', 'Crawfish', 20, 1, 'item_standard', 1, 424, '{}', 'Can be sold or crafted'),
	('Creeking_Thyme', 'Creeping Thyme', 10, 1, 'item_standard', 1, 142, '{}', 'Used for crafting'),
	('Creeking_Thyme_Seed', 'Creeping Thyme Seed', 10, 1, 'item_standard', 1, 143, '{}', 'Uused for farming'),
	('Creekplum', 'Creekplum', 10, 1, 'item_standard', 1, 144, '{}', 'Can be consumed'),
	('Creekplum_Seed', 'Creekplum Seed', 10, 1, 'item_standard', 1, 145, '{}', 'Used for farming'),
	('Crows_Garlic', 'Crows Garlic', 10, 1, 'item_standard', 1, 146, '{}', 'Used for crafting'),
	('Crows_Garlic_Seed', 'Crows Garlic Seed', 10, 1, 'item_standard', 1, 147, '{}', 'Used for farming'),
	('crow_c', 'Crow', 20, 1, 'item_standard', 1, 426, '{}', 'Can be sold or crafted'),
	('darub', 'Crane beak', 20, 1, 'item_standard', 1, 530, '{}', 'Can be sold or crafted'),
	('daruf', 'Crane feather', 20, 1, 'item_standard', 1, 529, '{}', 'Can be sold or crafted'),
	('dbcandle', 'Dbl Candle', 20, 1, 'item_standard', 1, 660, '{}', 'Home furnishing'),
	('decortent1', 'Decor Tent 1 Set', 20, 1, 'item_standard', 1, 600, '{}', 'Home furnishing'),
	('decortent2', 'Decor Tent 2 Set', 20, 1, 'item_standard', 1, 601, '{}', 'Home furnishing'),
	('decortent3', 'Decor Tent 3 Set', 20, 1, 'item_standard', 1, 602, '{}', 'Home furnishing'),
	('deerheart', 'Deer heart', 20, 1, 'item_standard', 1, 466, '{}', 'Can be sold or crafted'),
	('deerpelt', 'Deer Pelt', 20, 1, 'item_standard', 1, 758, '{}', 'Can be sold or crafted'),
	('deerskin', 'Deer skin', 20, 1, 'item_standard', 1, 465, '{}', 'Can be sold or crafted'),
	('deertaxi', 'Deer Taxidermy', 20, 1, 'item_standard', 1, 770, '{}', 'Didn\'t you say it was 16 points?'),
	('deer_pelt', 'Deer Pelt', 20, 1, 'item_standard', 1, 630, '{}', 'Can be sold or crafted'),
	('deer_taxidermy', 'Deer Taxidermy', 20, 1, 'item_standard', 1, 642, '{}', 'Didn\'t you say it was 16 points?'),
	('Desert_Sage', 'Desert Sage', 10, 1, 'item_standard', 1, 148, '{}', 'Used for crafting'),
	('Desert_Sage_Seed', 'Desert Sage Seed', 10, 1, 'item_standard', 1, 149, '{}', 'Used for farming'),
	('diamond', 'Diamond', 20, 1, 'item_standard', 1, 150, '{}', 'Can be sold'),
	('dleguans', 'Desert Iguana pelt', 20, 1, 'item_standard', 1, 551, '{}', 'Can be sold or crafted'),
	('dreamcatcher', 'Dream Catcher', 20, 1, 'item_standard', 1, 591, '{}', 'Home furnishing'),
	('Drink_For_Dog', 'Pet Water', 10, 1, 'item_standard', 1, 151, '{}', 'Pets get thirsty too'),
	('duckfat', 'Duck fat', 20, 1, 'item_standard', 1, 467, '{}', 'Can be sold or crafted'),
	('Duck_Egg', 'Duck Egg', 10, 1, 'item_standard', 1, 152, '{}', 'Can be sold or crafted'),
	('dynamite', 'Dynamite', 30, 1, 'item_standard', 1, 153, '{}', 'and what exactly do you need this for?'),
	('eaglef', 'Eagle feather', 20, 1, 'item_standard', 1, 468, '{}', 'Can be sold or crafted'),
	('eaglet', 'Eagle claws', 20, 1, 'item_standard', 1, 469, '{}', 'Can be sold or crafted'),
	('egg', 'Egg', 20, 1, 'item_standard', 1, 796, '{}', 'Can be sold or crafted'),
	('eggs', 'Egg', 50, 1, 'item_standard', 1, 154, '{}', 'Can be sold or crafted'),
	('egretb', 'Snowy Egret beak', 20, 1, 'item_standard', 1, 473, '{}', 'Can be sold or crafted'),
	('egretf', 'Snowy Egret feather', 20, 1, 'item_standard', 1, 472, '{}', 'Can be sold or crafted'),
	('elkantler', 'Elk antler', 20, 1, 'item_standard', 1, 474, '{}', 'Can be sold or crafted'),
	('elks', 'Vapiti pelt', 20, 1, 'item_standard', 1, 475, '{}', 'Can be sold or crafted'),
	('emerald', 'Emerald', 20, 1, 'item_standard', 1, 155, '{}', 'Can be sold'),
	('English_Mace', 'English Mace', 10, 1, 'item_standard', 1, 156, '{}', 'Can be sold or crafted'),
	('English_Mace_Seed', 'English Mace Seed', 10, 1, 'item_standard', 1, 157, '{}', 'Used for farming'),
	('Evergreen_Huckleberry', 'Evergreen Huckleberry', 10, 1, 'item_standard', 1, 158, '{}', 'Can be sold or crafted'),
	('Evergreen_Huckleberry_Seed', 'Evergreen Huckleberry Seed', 10, 1, 'item_standard', 1, 159, '{}', 'Used for farming'),
	('fan', 'Fan', 5, 1, 'item_standard', 1, 160, '{}', 'nice item'),
	('fancydouble', 'fancy double', 20, 1, 'item_standard', 1, 667, '{}', 'nice item'),
	('Fat', 'Animal Fat', 10, 1, 'item_standard', 1, 161, '{}', 'Can be sold or crafted'),
	('Feather', 'Feather', 20, 1, 'item_standard', 1, 162, '{}', 'Can be sold or crafted'),
	('Feed_For_Dog', 'Dog Food', 10, 1, 'item_standard', 1, 163, '{}', 'For growing big and strong'),
	('fertilizer', 'Fertilizer', 10, 1, 'item_standard', 1, 736, '{}', 'Used for farming'),
	('fertilizerbless', 'Blessed Fertilizer', 10, 1, 'item_standard', 1, 738, '{}', 'Used for farming'),
	('fertilizeregg', 'Fertilizer with Eggs', 10, 1, 'item_standard', 1, 737, '{}', 'Used for farming'),
	('fertilizerpro', 'Fertilizer with Produce', 10, 1, 'item_standard', 1, 740, '{}', 'Used for farming'),
	('fertilizerpulpsap', 'Fertilizer with Pulp/Sap', 10, 1, 'item_standard', 1, 741, '{}', 'Used for farming'),
	('fertilizersn', 'Fertilizer with Snake', 10, 1, 'item_standard', 1, 742, '{}', 'Used for farming'),
	('fertilizersq', 'Fertilizer with Squirrel', 10, 1, 'item_standard', 1, 743, '{}', 'Used for farming'),
	('fertilizersw', 'Fertilizer with Soft Wood', 10, 1, 'item_standard', 1, 745, '{}', 'Used for farming'),
	('fertilizersyn', 'Synful Fertilizer', 10, 1, 'item_standard', 1, 739, '{}', 'Used for farming'),
	('fertilizerwoj', 'Fertilizer with Wojape', 10, 1, 'item_standard', 1, 744, '{}', 'Used for farming'),
	('fibers', 'Fibers', 20, 1, 'item_standard', 0, 164, '{}', 'Can be sold or crafted'),
	('fish', 'Fish', 50, 1, 'item_standard', 1, 165, '{}', 'Can be sold or crafted'),
	('fishbait', 'Fishbait', 10, 1, 'item_standard', 1, 166, '{}', 'Used for fishing'),
	('fishchips', 'Fish and Chips', 10, 1, 'item_standard', 1, 167, '{}', 'Can be consumed'),
	('fishingrod', 'Fishing Rod', 1, 1, 'item_standard', 1, 980, '{}', 'nice item'),
	('fishmeat', 'Bigfish Meat', 20, 1, 'item_standard', 1, 572, '{}', 'Can be sold or crafted'),
	('flag', 'Camp Flag', 10, 1, 'item_standard', 1, 168, '{}', 'nice item'),
	('flowerboxes', 'Flower Boxes', 20, 1, 'item_standard', 1, 628, '{}', 'nice item'),
	('foodbarrel', 'Food Barrel', 20, 1, 'item_standard', 1, 764, '{}', 'nice item'),
	('food_barrel', 'Food Barrel', 20, 1, 'item_standard', 1, 636, '{}', 'nice item'),
	('foxskin', 'Foxskin', 20, 1, 'item_standard', 1, 512, '{}', 'Can be sold or crafted'),
	('foxt', 'Fox tooth', 20, 1, 'item_standard', 1, 513, '{}', 'Can be sold or crafted'),
	('friedtater', 'Fried Taters', 10, 1, 'item_standard', 1, 169, '{}', 'Can be consumed'),
	('frogbull2_c', 'Poisoned Bullfrog', 20, 1, 'item_standard', 1, 428, '{}', 'Can be sold or crafted'),
	('frogbull_c', 'Bullfrog', 20, 1, 'item_standard', 1, 427, '{}', 'Can be sold or crafted'),
	('fsnakes', 'Blacktailed rattlesnake pelt', 20, 1, 'item_standard', 1, 488, '{}', 'Can be sold or crafted'),
	('game', 'Game Meat', 20, 1, 'item_standard', 1, 570, '{}', 'Can be sold or crafted'),
	('Gamey_Meat', 'Gamey Meat', 10, 1, 'item_standard', 1, 170, '{}', 'Can be sold or crafted'),
	('Gator_Egg_3', 'Aligator Egg 3', 10, 1, 'item_standard', 1, 171, '{}', 'Can be sold or crafted'),
	('Gator_Egg_4', 'Aligator Egg 4', 10, 1, 'item_standard', 1, 172, '{}', 'Can be sold or crafted'),
	('Gator_Egg_5', 'Aligator Egg 5', 10, 1, 'item_standard', 1, 173, '{}', 'Can be sold or crafted'),
	('gbarrelx', 'Gun Barrel', 20, 1, 'item_standard', 1, 761, '{}', 'nice item'),
	('gbears', 'Grizzly Bear skin', 20, 1, 'item_standard', 1, 453, '{}', 'Can be sold or crafted'),
	('ginsengtea', 'Ginseng Tea', 10, 1, 'item_standard', 1, 174, '{}', 'Can be consumed'),
	('glassbottle', 'Glass Bottle', 15, 1, 'item_standard', 1, 175, '{}', 'nice item'),
	('gleguans', 'Green Iguana pelt', 20, 1, 'item_standard', 1, 552, '{}', 'Can be sold or crafted'),
	('goathead', 'Goat head', 20, 1, 'item_standard', 1, 556, '{}', 'Can be sold'),
	('goats', 'Goat pelt', 20, 1, 'item_standard', 1, 555, '{}', 'Can be sold or crafted'),
	('goldbar', 'GoldBar', 5, 1, 'item_standard', 1, 176, '{}', 'Can be sold or used as currency'),
	('Golden_Currant', 'Golden Currant', 10, 1, 'item_standard', 1, 177, '{}', 'Can be sold or crafted'),
	('Golden_Currant_Seed', 'Golden Currant Seed', 10, 1, 'item_standard', 1, 178, '{}', 'Used for farming'),
	('goldfish', 'Gold Fish', 10, 1, 'item_standard', 0, 179, '{}', 'nice item'),
	('goldnugget', 'Gold Nugget', 50, 1, 'item_standard', 0, 899, '{}', 'Can be sold or crafted'),
	('goldpan', 'Gold pan', 10, 1, 'item_standard', 1, 181, '{}', 'Good luck out there'),
	('goldring', 'Gold Ring', 10, 1, 'item_standard', 1, 182, '{}', 'Can be sold'),
	('Gold_For_Horse', 'Gold Horse Elixir', 20, 1, 'item_standard', 1, 991, '{}', 'Full Outer Cores (temp)'),
	('gold_nugget', 'Gold nugget', 30, 1, 'item_standard', 0, 180, '{}', 'Can be sold or crafted'),
	('gooseb', 'Goose beak', 20, 1, 'item_standard', 1, 532, '{}', 'Can be sold or crafted'),
	('goosef', 'Goose feather', 20, 1, 'item_standard', 1, 531, '{}', 'Can be sold or crafted'),
	('Goose_Egg_4', 'Goose Egg', 10, 1, 'item_standard', 1, 183, '{}', 'Can be sold or crafted'),
	('guitar', 'Classic Guitar', 1, 1, 'item_standard', 1, 341, '{}', 'nice item'),
	('gun_barrel', 'Gun Barrel', 20, 1, 'item_standard', 1, 633, '{}', 'nice item'),
	('gypsywagon', 'Gypsys Wagon Set', 20, 1, 'item_standard', 1, 585, '{}', 'nice item'),
	('hairpomade', 'Hair Pomade', 5, 1, 'item_standard', 1, 184, '{}', 'nice item'),
	('handcuffs', 'Handcuffs', 10, 1, 'item_standard', 1, 185, '{}', 'nice item'),
	('hatchet', 'Hatchet', 1, 1, 'item_standard', 1, 186, '{}', 'Used for chopping'),
	('hawkf', 'Hawk feather', 20, 1, 'item_standard', 1, 535, '{}', 'Can be sold or crafted'),
	('hawkt', 'Hawk claws', 20, 1, 'item_standard', 1, 536, '{}', 'Can be sold or crafted'),
	('Health_For_Dog', 'Pet Bandages', 10, 1, 'item_standard', 1, 187, '{}', 'Dog Medication (for vet use only)'),
	('Heal_For_Horse', 'Horse Medicine', 20, 1, 'item_standard', 1, 992, '{}', 'Horse Medication (for vet use only)'),
	('hemp', 'Hemp', 10, 1, 'item_standard', 1, 188, '{}', 'Can be sold or crafted'),
	('hemp_cig', 'Hemp Cigarette', 1, 1, 'item_standard', 1, 189, '{}', 'Wanna get high?'),
	('hemp_seed', 'Hemp Seed', 20, 1, 'item_standard', 1, 615, '{}', 'Used for farming'),
	('herbal_medicine', 'Herbal Medicine', 20, 1, 'item_standard', 1, 338, '{}', 'Feel better now'),
	('herbal_tonic', 'Herbal Tonic', 20, 1, 'item_standard', 1, 339, '{}', 'Feel better now'),
	('herbmed', 'Herbal Remedy', 10, 1, 'item_standard', 1, 190, '{}', 'Feel better now'),
	('herb_vanilla', 'Vanilla Flower', 20, 1, 'item_standard', 0, 307, '{}', 'Can be sold or crafted'),
	('heroin', 'Heroin', 5, 1, 'item_standard', 1, 191, '{}', 'Feeeeeeeeeeelllllllliiiiinnnnnnn Gggggoooooooooddddddd'),
	('herptile', 'Herptile meat', 20, 1, 'item_standard', 1, 573, '{}', 'Can be sold or crafted'),
	('hitchingpost', 'Hitching Post', 20, 1, 'item_standard', 1, 580, '{}', 'Home Furnishing'),
	('hoe', 'Garden Hoe', 10, 1, 'item_standard', 1, 679, '{}', 'Used for farming'),
	('honey', 'Honey', 10, 1, 'item_standard', 1, 192, '{}', 'Can be sold or crafted'),
	('hop', 'Hop', 10, 1, 'item_standard', 1, 685, '{}', 'Can be sold or crafted'),
	('hop_seed', 'Hop Seed', 10, 1, 'item_standard', 1, 684, '{}', 'Used for farming'),
	('horsebrush', 'Horse Brush', 5, 1, 'item_standard', 1, 193, '{}', 'Keep your horse clean and happy'),
	('horsehitches', 'Horse Hitches Set', 20, 1, 'item_standard', 1, 603, '{}', 'nice item'),
	('horsemeal', 'Horse ration', 10, 1, 'item_standard', 1, 348, '{}', 'Food for horse'),
	('Hummingbird_Sage', 'Hummingbird Sage', 10, 1, 'item_standard', 1, 194, '{}', 'Can be sold or crafted'),
	('Hummingbird_Sage_Seed', 'Hummingbird Sage Seed', 10, 1, 'item_standard', 1, 195, '{}', 'Used for farming'),
	('hwood', 'Hard Wood', 20, 1, 'item_standard', 0, 196, '{}', 'Can be sold or crafted'),
	('Indian_Tobbaco', 'Indian Tobbaco', 20, 1, 'item_standard', 1, 197, '{}', 'Can be sold or crafted'),
	('Indian_Tobbaco_Seed', 'Indian Tobbaco Seed', 10, 1, 'item_standard', 1, 198, '{}', 'Used for farming'),
	('iron', 'Iron Ore', 30, 1, 'item_standard', 1, 199, '{}', 'Can be sold or crafted'),
	('ironbar', 'Iron Bar', 30, 1, 'item_standard', 1, 200, '{}', 'Can be sold or crafted'),
	('ironextract', 'Iron Extract', 1, 1, 'item_standard', 0, 201, '{}', 'nice item'),
	('ironhammer', 'Iron Hammer', 5, 1, 'item_standard', 1, 202, '{}', 'Used for crafting'),
	('kbirdb', 'Great Blue Heron beak', 20, 1, 'item_standard', 1, 534, '{}', 'Can be sold or crafted'),
	('kbirdf', 'Great Blue Heron feather', 20, 1, 'item_standard', 1, 533, '{}', 'Can be sold or crafted'),
	('kitchencounter', 'Kitchen Counter', 20, 1, 'item_standard', 1, 611, '{}', 'Home furnishing'),
	('kit_bandana', 'Bandana', 2, 1, 'item_standard', 1, 203, '{}', 'We already know you ugly'),
	('kit_repair_wagon', 'Wagon Repair Kit', 1, 1, 'item_standard', 1, 1000, '{}', 'Tools for cart repair'),
	('lamppost1', 'Lamp Post 1 Set', 20, 1, 'item_standard', 1, 606, '{}', 'nice item'),
	('lamppost2', 'Lamp Post 2 Set', 20, 1, 'item_standard', 1, 607, '{}', 'nice item'),
	('lanterna', 'Lantern', 20, 1, 'item_standard', 1, 659, '{}', 'Can you see me?'),
	('leather', 'Leather', 50, 1, 'item_standard', 1, 204, '{}', 'Can be sold or crafted'),
	('leatherchair', 'Leather Chair', 20, 1, 'item_standard', 1, 748, '{}', 'Home furnishing'),
	('leather_chair', 'Leather Chair', 20, 1, 'item_standard', 1, 620, '{}', 'Home furnishing'),
	('legalbook', 'Legal Book', 1, 1, 'item_standard', 1, 892, '{}', 'I am the law'),
	('legaligators', 'Legendary Alligator pelt', 20, 1, 'item_standard', 1, 417, '{}', 'Can be sold or crafted'),
	('legaligators1', 'Legendary Teca Alligator pelt', 20, 1, 'item_standard', 1, 400, '{}', 'Can be sold or crafted'),
	('legaligators2', 'Legendary Sun Alligator pelt', 20, 1, 'item_standard', 1, 401, '{}', 'Can be sold or crafted'),
	('legaligators3', 'Legendary Banded Alligator pelt', 20, 1, 'item_standard', 1, 402, '{}', 'Can be sold or crafted'),
	('legalpaper', 'Legal Paper', 4, 1, 'item_standard', 1, 891, '{}', 'nice item'),
	('legbears1', 'Legendary Deadly Bear pelt', 20, 1, 'item_standard', 1, 376, '{}', 'Can be sold or crafted'),
	('legbears2', 'Legendary Owiza Bear pelt', 20, 1, 'item_standard', 1, 377, '{}', 'Can be sold or crafted'),
	('legbears3', 'Legendary Ridgeback Spirit Bear pelt', 20, 1, 'item_standard', 1, 378, '{}', 'Can be sold or crafted'),
	('legbears4', 'Legendary Golden Spirit Bear pelt', 20, 1, 'item_standard', 1, 379, '{}', 'Can be sold or crafted'),
	('legbeavers1', 'Legendary Grey Beaver pelt', 20, 1, 'item_standard', 1, 397, '{}', 'Can be sold or crafted'),
	('legbeavers2', 'Legendary White Beaver pelt', 20, 1, 'item_standard', 1, 398, '{}', 'Can be sold or crafted'),
	('legbeavers3', 'Legendary Black Beaver pelt', 20, 1, 'item_standard', 1, 399, '{}', 'Can be sold or crafted'),
	('legbeawers', 'Legendary Beaver pelt', 20, 1, 'item_standard', 1, 411, '{}', 'Can be sold or crafted'),
	('legbisonhorn', 'Legendary Bison Horns', 20, 1, 'item_standard', 1, 353, '{}', 'Can be sold or crafted'),
	('legbisons', 'Legendary Bison pelt', 20, 1, 'item_standard', 1, 416, '{}', 'Can be sold or crafted'),
	('legbisons1', 'Legendary Tatanka Bison pelt', 20, 1, 'item_standard', 1, 365, '{}', 'Can be sold or crafted'),
	('legbisons2', 'Legendary Winyan Bison pelt', 20, 1, 'item_standard', 1, 366, '{}', 'Can be sold or crafted'),
	('legbisons3', 'Legendary Payata Bison pelt', 20, 1, 'item_standard', 1, 367, '{}', 'Can be sold or crafted'),
	('legbisonstak', 'Legendary Takanta Bison pelt', 20, 1, 'item_standard', 1, 415, '{}', 'Can be sold or crafted'),
	('legboars', 'Legendary Boar pelt', 20, 1, 'item_standard', 1, 414, '{}', 'Can be sold or crafted'),
	('legboars1', 'Legendary Cogi Boar pelt', 20, 1, 'item_standard', 1, 393, '{}', 'Can be sold or crafted'),
	('legboars2', 'Legendary Wakpa Boar pelt', 20, 1, 'item_standard', 1, 394, '{}', 'Can be sold or crafted'),
	('legboars3', 'Legendary Icahi Boar pelt', 20, 1, 'item_standard', 1, 395, '{}', 'Can be sold or crafted'),
	('legboars4', 'Legendary Wildhog pelt', 20, 1, 'item_standard', 1, 396, '{}', 'Can be sold or crafted'),
	('legbucks', 'Legendary Buck skin', 20, 1, 'item_standard', 1, 410, '{}', 'Can be sold or crafted'),
	('legbucks1', 'Legendary Buck pelt', 20, 1, 'item_standard', 1, 368, '{}', 'Can be sold or crafted'),
	('legbucks2', 'Legendary Mudrunner Buck pelt', 20, 1, 'item_standard', 1, 369, '{}', 'Can be sold or crafted'),
	('legbucks3', 'Legendary Snow Buck pelt', 20, 1, 'item_standard', 1, 370, '{}', 'Can be sold or crafted'),
	('legbucks4', 'Legendary Shadow Buck pelt', 20, 1, 'item_standard', 1, 371, '{}', 'Can be sold or crafted'),
	('legcougars', 'Legendary Cougar skin', 20, 1, 'item_standard', 1, 409, '{}', 'Can be sold or crafted'),
	('legcougars1', 'Legendary Iguga Cougar pelt', 20, 1, 'item_standard', 1, 389, '{}', 'Can be sold or crafted'),
	('legcougars2', 'Legendary Maza Cougar pelt', 20, 1, 'item_standard', 1, 390, '{}', 'Can be sold or crafted'),
	('legcougars3', 'Legendary Sapa Cougar pelt', 20, 1, 'item_standard', 1, 391, '{}', 'Can be sold or crafted'),
	('legcougars4', 'Legendary Black Cougar pelt', 20, 1, 'item_standard', 1, 392, '{}', 'Can be sold or crafted'),
	('legcoyotes', 'Legendary Coyote skin', 20, 1, 'item_standard', 1, 408, '{}', 'Can be sold or crafted'),
	('legcoyotes1', 'Legendary Red Streak Coyote pelt', 20, 1, 'item_standard', 1, 386, '{}', 'Can be sold or crafted'),
	('legcoyotes2', 'Legendary Midnight Paw Coyote pelt', 20, 1, 'item_standard', 1, 387, '{}', 'Can be sold or crafted'),
	('legcoyotes3', 'Legendary Milk Coyote pelt', 20, 1, 'item_standard', 1, 388, '{}', 'Can be sold or crafted'),
	('legelkantler', 'Legendary Elk Antlers', 20, 1, 'item_standard', 1, 355, '{}', 'Can be sold or crafted'),
	('legelks', 'Legendary Elk pelt', 20, 1, 'item_standard', 1, 403, '{}', 'Can be sold or crafted'),
	('legelks1', 'Legendary Katata Elk pelt', 20, 1, 'item_standard', 1, 362, '{}', 'Can be sold or crafted'),
	('legelks2', 'Legendary Ozula Elk pelt', 20, 1, 'item_standard', 1, 363, '{}', 'Can be sold or crafted'),
	('legelks3', 'Legendary Inahme Elk pelt', 20, 1, 'item_standard', 1, 364, '{}', 'Can be sold or crafted'),
	('legendbuckantler', 'Legendary Buck Antlers', 20, 1, 'item_standard', 1, 356, '{}', 'Can be sold or crafted'),
	('legendsnakes', 'Legendary Boa pelt', 20, 1, 'item_standard', 1, 418, '{}', 'Can be sold or crafted'),
	('legfoxs2', 'Legendary Marble Fox pelt', 20, 1, 'item_standard', 1, 360, '{}', 'Can be sold or crafted'),
	('legfoxs3', 'Legendary Cross Fox pelt', 20, 1, 'item_standard', 1, 361, '{}', 'Can be sold or crafted'),
	('legfoxskin', 'Legendary Fox skin', 20, 1, 'item_standard', 1, 413, '{}', 'Can be sold or crafted'),
	('leggbears', 'Legendary Bear skin', 20, 1, 'item_standard', 1, 404, '{}', 'Can be sold or crafted'),
	('legmooseantler', 'Legendary Moose Antlers', 20, 1, 'item_standard', 1, 352, '{}', 'Can be sold or crafted'),
	('legmooses', 'Legendary Moose pelt', 20, 1, 'item_standard', 1, 405, '{}', 'Can be sold or crafted'),
	('legmooses1', 'Legendary Snowflake Moose pelt', 20, 1, 'item_standard', 1, 357, '{}', 'Can be sold or crafted'),
	('legmooses2', 'Legendary Knight Moose pelt', 20, 1, 'item_standard', 1, 358, '{}', 'Can be sold or crafted'),
	('legmooses3', 'Legendary Rudy Moose pelt', 20, 1, 'item_standard', 1, 359, '{}', 'Can be sold or crafted'),
	('legpanthers1', 'Legendary Nightwalker Panther pelt', 20, 1, 'item_standard', 1, 383, '{}', 'Can be sold or crafted'),
	('legpanthers2', 'Legendary Ghost Panther pelt', 20, 1, 'item_standard', 1, 384, '{}', 'Can be sold or crafted'),
	('legpanthers3', 'Legendary Iwakta Panther pelt', 20, 1, 'item_standard', 1, 385, '{}', 'Can be sold or crafted'),
	('legprongs', 'Legendary Pronghorn skin', 20, 1, 'item_standard', 1, 407, '{}', 'Can be sold or crafted'),
	('legramhorn', 'Legendary Ram Horns', 20, 1, 'item_standard', 1, 354, '{}', 'Can be sold or crafted'),
	('legrams', 'Legendary Ram pelt', 20, 1, 'item_standard', 1, 412, '{}', 'Can be sold or crafted'),
	('legrams1', 'Legendary Gabbro Horn Ram pelt', 20, 1, 'item_standard', 1, 372, '{}', 'Can be sold or crafted'),
	('legrams2', 'Legendary Chalk Horn Ram pelt', 20, 1, 'item_standard', 1, 373, '{}', 'Can be sold or crafted'),
	('legrams3', 'Legendary Rutile Horn Ram pelt', 20, 1, 'item_standard', 1, 374, '{}', 'Can be sold or crafted'),
	('legrams4', 'Legendary GreatHorn Ram pelt', 20, 1, 'item_standard', 1, 375, '{}', 'Can be sold or crafted'),
	('legwolfpelt', 'Legendary Wolf skin', 20, 1, 'item_standard', 1, 406, '{}', 'Can be sold or crafted'),
	('legwolfs1', 'Legendary Emerald Wolf pelt', 20, 1, 'item_standard', 1, 380, '{}', 'Can be sold or crafted'),
	('legwolfs2', 'Legendary Onyx Wolf pelt', 20, 1, 'item_standard', 1, 381, '{}', 'Can be sold or crafted'),
	('legwolfs3', 'Legendary Moonstone Wolf pelt', 20, 1, 'item_standard', 1, 382, '{}', 'Can be sold or crafted'),
	('lizardl', 'Lizard foot', 20, 1, 'item_standard', 1, 554, '{}', 'Can be sold or crafted'),
	('lizards', 'Lizard pelt', 20, 1, 'item_standard', 1, 553, '{}', 'Can be sold or crafted'),
	('lockpick', 'Lockpick', 5, 1, 'item_standard', 1, 205, '{}', 'Used for breaking locks'),
	('lockpickmold', 'Lockpick Mold', 5, 1, 'item_standard', 1, 206, '{}', 'nice item'),
	('logbechs', 'Log Bench 2', 20, 1, 'item_standard', 1, 775, '{}', 'Home furnishing'),
	('logbench', 'Log Bench 1', 20, 1, 'item_standard', 1, 774, '{}', 'Home furnishing'),
	('log_bencha', 'Log Bench 1', 20, 1, 'item_standard', 1, 646, '{}', 'Home furnishing'),
	('log_benchb', 'Log Bench 2', 20, 1, 'item_standard', 1, 647, '{}', 'Home furnishing'),
	('loonb', 'Common loon beak', 20, 1, 'item_standard', 1, 538, '{}', 'Can be sold or crafted'),
	('loonf', 'Common loon feather', 20, 1, 'item_standard', 1, 537, '{}', 'Can be sold or crafted'),
	('loungechair', 'Lounge Chair', 20, 1, 'item_standard', 1, 598, '{}', 'Home furnishing'),
	('loungechair2', 'Lounge Chair 2', 20, 1, 'item_standard', 1, 599, '{}', 'Home furnishing'),
	('lumberaxe', 'Lumber Axe', 1, 1, 'item_standard', 1, 345, '{}', 'Used for chopping'),
	('mackerel', 'Mackerel', 10, 1, 'item_standard', 0, 207, '{}', 'Can be sold or crafted'),
	('marriagebook', 'Marriage Book', 1, 1, 'item_standard', 1, 894, '{}', 'Record of marriages'),
	('marriagecertification', 'Marriage Certify', 2, 1, 'item_standard', 1, 895, '{}', 'Certificate of marriage'),
	('mashalaskan', 'Alaskan Gin Mash', 20, 1, 'item_standard', 1, 824, '{}', 'Used for crafting'),
	('mashamerican', 'American Gin Mash', 20, 1, 'item_standard', 1, 825, '{}', 'Used for crafting'),
	('mashapple', 'Apple Mash', 20, 1, 'item_standard', 1, 826, '{}', 'Used fro crafting'),
	('mashblackberry', 'Blackberry Mash', 20, 1, 'item_standard', 1, 827, '{}', 'Used fro crafting'),
	('mashblackberry90p', 'Blackberry Mash 90p', 20, 1, 'item_standard', 1, 828, '{}', 'Used for crafting'),
	('mashpeach', 'Peach Mash', 20, 1, 'item_standard', 1, 829, '{}', 'Used fro crafting'),
	('mashplum', 'Plum Mash', 20, 1, 'item_standard', 1, 830, '{}', 'Used fro crafting'),
	('mashraspberry', 'Raspberry Mash', 20, 1, 'item_standard', 1, 831, '{}', 'Used fro crafting'),
	('mashraspberry90p', 'Raspberry Mash 90p', 20, 1, 'item_standard', 1, 832, '{}', 'Used fro crafting'),
	('mashstrong', 'Strong Mash Batch', 20, 1, 'item_standard', 1, 833, '{}', 'Used fro crafting'),
	('meat', 'Meat', 20, 1, 'item_standard', 1, 208, '{}', 'Can be sold or crafted'),
	('milk', 'Milk', 50, 1, 'item_standard', 1, 209, '{}', 'Can be sold or crafted'),
	('Milk_Weed', 'Milk Weed', 10, 1, 'item_standard', 1, 210, '{}', 'Can be sold or crafted'),
	('Milk_Weed_Seed', 'Milk Weed Seed', 10, 1, 'item_standard', 1, 211, '{}', 'Used for farming'),
	('moonshine', 'Moonshine', 10, 1, 'item_standard', 1, 212, '{}', 'She gone...this will help'),
	('mooseantler', 'Moose Antlers', 20, 1, 'item_standard', 1, 548, '{}', 'Can be sold or crafted'),
	('mooses', 'Moose pelt', 20, 1, 'item_standard', 1, 549, '{}', 'Can be sold or crafted'),
	('morpcert', 'Morphine Perscription', 10, 1, 'item_standard', 1, 213, '{}', 'Medicinal use only?...yeah, I believe you'),
	('morphine', 'Morphine', 10, 1, 'item_standard', 1, 214, '{}', 'I don\'t want to feel anymore'),
	('mountainmen', 'Mountain Camp Set', 20, 1, 'item_standard', 1, 608, '{}', 'nice item'),
	('mp001_p_mp_still02x', 'Brennerei', 1, 1, 'item_standard', 1, 215, '{}', 'nice item'),
	('muskrats', 'Muskrat skin', 20, 1, 'item_standard', 1, 547, '{}', 'Can be sold or crafted'),
	('Mutton', 'Mutton', 20, 1, 'item_standard', 1, 216, '{}', 'Can be sold or crafted'),
	('nails', 'Nails', 40, 1, 'item_standard', 1, 217, '{}', 'Used for crafting'),
	('nativebasket1', 'Native Basket 1', 20, 1, 'item_standard', 1, 593, '{}', 'nice item'),
	('nativebasket2', 'Native Basket 2', 20, 1, 'item_standard', 1, 594, '{}', 'nice item'),
	('nativedecor', 'Native Decor Set', 20, 1, 'item_standard', 1, 584, '{}', 'Home furnishing'),
	('nativepot', 'Native Pot', 20, 1, 'item_standard', 1, 592, '{}', 'nice item'),
	('nativeskull', 'Native Decor 1', 20, 1, 'item_standard', 1, 595, '{}', 'Home furnishing'),
	('naturalwagon', 'Naturalists Wagon Set', 20, 1, 'item_standard', 1, 605, '{}', 'nice item'),
	('newspaper', 'NewsPaper', 20, 1, 'item_standard', 1, 218, '{}', 'What happened last week'),
	('nightstand', 'night stand', 20, 1, 'item_standard', 1, 653, '{}', 'Home furnishing'),
	('nitrite', 'Nitrite', 20, 1, 'item_standard', 1, 219, '{}', 'I know what you are doing...'),
	('nitroglyserolia', 'Nitroglycerol', 30, 1, 'item_standard', 1, 220, '{}', 'Careful now....'),
	('normaltable', 'Table', 20, 1, 'item_standard', 1, 750, '{}', 'Home furnishing'),
	('notebook', 'Notebook', 5, 1, 'item_standard', 1, 221, '{}', 'What you got in there?'),
	('obed', 'Old bed', 20, 1, 'item_standard', 1, 664, '{}', 'Home furnishing'),
	('Oleander_Sage', 'Oleander Sage', 10, 1, 'item_standard', 1, 222, '{}', 'Can be sold or crafted'),
	('Oleander_Sage_Seed', 'Oleander Sage Seed', 10, 1, 'item_standard', 1, 223, '{}', 'Used for farming'),
	('opossumc', 'Opossum claws', 20, 1, 'item_standard', 1, 515, '{}', 'Can be sold or crafted'),
	('opossums', 'Opossum skin', 20, 1, 'item_standard', 1, 514, '{}', 'Can be sold or crafted'),
	('orden_presidente', 'Order of the President', 10, 1, 'item_standard', 0, 224, '{}', 'nice item'),
	('Oregano', 'Oregano', 10, 1, 'item_standard', 1, 225, '{}', 'Can be sold or crafted'),
	('Oregano_Seed', 'Oregano Seed', 10, 1, 'item_standard', 1, 226, '{}', 'Used for famring'),
	('oriole2_c', 'Hooded Oriole', 20, 1, 'item_standard', 1, 430, '{}', 'Can be sold'),
	('oriole_c', 'Oriole', 20, 1, 'item_standard', 1, 429, '{}', 'Can be sold'),
	('owlf', 'Owl feather', 20, 1, 'item_standard', 1, 539, '{}', 'Can be sold or crafted'),
	('owlt', 'Owl claws', 20, 1, 'item_standard', 1, 540, '{}', 'Can be sold or crafted'),
	('oxhorn', 'Angus Bull horn', 20, 1, 'item_standard', 1, 545, '{}', 'Can be sold or crafted'),
	('oxs', 'Angus Bull pelt', 20, 1, 'item_standard', 1, 546, '{}', 'Can be sold or crafted'),
	('panthere', 'Panther eyes', 20, 1, 'item_standard', 1, 564, '{}', 'Can be sold or crafted'),
	('panthers', 'Panther skin', 20, 1, 'item_standard', 1, 563, '{}', 'Can be sold or crafted'),
	('paper', 'Paper', 20, 1, 'item_standard', 1, 227, '{}', 'nice item'),
	('parasol', 'Parasol', 1, 1, 'item_standard', 1, 343, '{}', 'Home furnishing'),
	('Parasol_Mushroom', 'Parasol Mushroom', 10, 1, 'item_standard', 1, 228, '{}', 'Can be sold or crafted'),
	('Parasol_Mushroom_Seed', 'Parasol Mushroom Spores', 10, 1, 'item_standard', 1, 229, '{}', 'Used for farming'),
	('peachseeds', 'Peach Seeds', 10, 1, 'item_standard', 1, 735, '{}', 'Used for farming'),
	('peasantb', 'Pheasant beak', 20, 1, 'item_standard', 1, 518, '{}', 'Can be sold or crafted'),
	('peasantf', 'Pheasant feather', 20, 1, 'item_standard', 1, 517, '{}', 'Can be sold or crafted'),
	('pecaris', 'Peccary pelt', 20, 1, 'item_standard', 1, 550, '{}', 'Can be sold or crafted'),
	('pelicanb', 'Pelican beak', 20, 1, 'item_standard', 1, 520, '{}', 'Can be sold or crafted'),
	('pelicanf', 'Pelican feather', 20, 1, 'item_standard', 1, 519, '{}', 'Can be sold or crafted'),
	('pen', 'Pen', 2, 1, 'item_standard', 0, 896, '{}', 'nice item'),
	('pheasant_taxidermy', 'Pheasant Taxidermy', 20, 1, 'item_standard', 1, 641, '{}', 'nice item'),
	('phestaxi', 'Pheasant Taxidermy', 20, 1, 'item_standard', 1, 769, '{}', 'nice item'),
	('pickaxe', 'Pickaxe', 1, 1, 'item_standard', 0, 230, '{}', 'Used for mining'),
	('pigeon_c', 'Pigeon', 20, 1, 'item_standard', 1, 431, '{}', 'Can be sold'),
	('pigs', 'Pig pelt', 20, 1, 'item_standard', 1, 516, '{}', 'Can be sold or crafted'),
	('pipe', 'Pipe', 5, 1, 'item_standard', 1, 231, '{}', 'Aren\'t you the proper gentleman'),
	('pipecopper', 'Copper Pipe', 5, 1, 'item_standard', 1, 835, '{}', 'Aren\'t you the proper gentleman'),
	('planttrimmer', 'Plant Trimmer', 10, 1, 'item_standard', 1, 678, '{}', 'nice item'),
	('pocket_watch', 'Pocket Watch', 5, 1, 'item_standard', 1, 232, '{}', 'What time is it?'),
	('pocket_watch_gold', 'Gold Pocket Watch', 1, 1, 'item_standard', 1, 997, '{}', 'What time is it?'),
	('pocket_watch_platinum', 'Platinum Pocket Watch', 1, 1, 'item_standard', 1, 999, '{}', 'What time is it?'),
	('pocket_watch_silver', 'Silver Pocket Watch', 1, 1, 'item_standard', 1, 998, '{}', 'What time is it?'),
	('pokerset', 'Poker Table Set', 20, 1, 'item_standard', 1, 579, '{}', 'Home furnishing'),
	('pork', 'Pork', 20, 1, 'item_standard', 1, 571, '{}', 'Can be sold or crafted'),
	('porkfat', 'Pig fat', 20, 1, 'item_standard', 1, 458, '{}', 'Can be sold or crafted'),
	('pot', 'Distillery Pot', 1, 1, 'item_standard', 1, 836, '{}', 'Whatcha makin\' there?'),
	('pota', 'House Pot', 20, 1, 'item_standard', 1, 626, '{}', 'Home furnishing'),
	('potato', 'Potato', 20, 1, 'item_standard', 1, 233, '{}', 'Can be sold or crafted'),
	('potatoseed', 'Potato Seed', 10, 1, 'item_standard', 1, 731, '{}', 'Used for farming'),
	('prairib', 'Prairie chicken beak', 20, 1, 'item_standard', 1, 509, '{}', 'Can be sold or crafted'),
	('Prairie_Poppy', 'Prairie Poppy', 10, 1, 'item_standard', 1, 234, '{}', 'Can be sold or crafted'),
	('Prairie_Poppy_Seed', 'Prairie Poppy Seed', 10, 1, 'item_standard', 1, 235, '{}', 'Used for farming'),
	('prairif', 'Prairie chicken feather', 20, 1, 'item_standard', 1, 508, '{}', 'Can be sold or crafted'),
	('pronghornh', 'Pronghorn horn', 20, 1, 'item_standard', 1, 511, '{}', 'Can be sold or crafted'),
	('prongs', 'Pronghorn skin', 20, 1, 'item_standard', 1, 510, '{}', 'Can be sold or crafted'),
	('provision_coal', 'Zinc Bar', 50, 1, 'item_standard', 0, 900, '{}', 'nice item'),
	('provision_jail_keys', 'Jail Keys', 10, 1, 'item_standard', 1, 236, '{}', 'Locks/Unlocks cells'),
	('pulp', 'Pulp', 20, 1, 'item_standard', 0, 237, '{}', 'Can be sold or crafted'),
	('p_baitBread01x', 'Bread Bait', 20, 1, 'item_standard', 1, 838, '{}', 'Used for fishing'),
	('p_baitCheese01x', 'Cheese Bait', 10, 1, 'item_standard', 1, 940, '{}', 'Used for fishing'),
	('p_baitCorn01x', 'Corn Bait', 10, 1, 'item_standard', 1, 939, '{}', 'Used for fishing'),
	('p_baitCricket01x', 'Cricket Bait', 10, 1, 'item_standard', 1, 942, '{}', 'Used for fishing'),
	('p_baitWorm01x', 'Worm Bait', 10, 1, 'item_standard', 1, 941, '{}', 'Used for fishing'),
	('p_barrelmoonshine', 'Barrel', 1, 1, 'item_standard', 1, 238, '{}', 'nice item'),
	('p_crawdad01x', 'Crawfish Bait', 10, 1, 'item_standard', 1, 943, '{}', 'nice item'),
	('p_FinisdFishlure01x', 'Fish Lure', 10, 1, 'item_standard', 1, 945, '{}', 'Used for fishing'),
	('p_finisdfishlurelegendary01x', 'Legendary Fish Lure', 10, 1, 'item_standard', 1, 948, '{}', 'Used for fishing'),
	('p_finishdcrawd01x', 'Crawfish Lure', 10, 1, 'item_standard', 1, 946, '{}', 'Used for fishing'),
	('p_finishdcrawdlegendary01x', 'Legendary Crawfish Lure', 10, 1, 'item_standard', 1, 949, '{}', 'Used for fishing'),
	('p_finishedragonfly01x', 'Dragonfly Lure', 10, 1, 'item_standard', 1, 944, '{}', 'Used for fishing'),
	('p_finishedragonflylegendary01x', 'Legendary Dragonfly Lure', 10, 1, 'item_standard', 1, 947, '{}', 'Used for fishing'),
	('p_lgoc_spinner_v4', 'Spinner V4', 10, 1, 'item_standard', 1, 950, '{}', 'Used for fishing'),
	('p_lgoc_spinner_v6', 'Spinner V6', 10, 1, 'item_standard', 1, 951, '{}', 'Used for fishing'),
	('quailb', 'Quail beak', 20, 1, 'item_standard', 1, 471, '{}', 'Can be sold or crafted'),
	('quailf', 'Quail feather', 20, 1, 'item_standard', 1, 470, '{}', 'Can be sold or crafted'),
	('quartz', 'Quartz', 20, 1, 'item_standard', 1, 239, '{}', 'Can be sold'),
	('rabbitpaw', 'Rabbitfoot', 20, 1, 'item_standard', 1, 507, '{}', 'Can be sold or crafted'),
	('rabbits', 'Rabbitskin', 20, 1, 'item_standard', 1, 506, '{}', 'Can be sold or crafted'),
	('raccoons', 'Raccoon skin', 20, 1, 'item_standard', 1, 504, '{}', 'Can be sold or crafted'),
	('raccoont', 'Raccoon tooth', 20, 1, 'item_standard', 1, 505, '{}', 'Can be sold or crafted'),
	('rajahdysoljy', 'Explosive Oil', 30, 1, 'item_standard', 1, 240, '{}', 'nice item'),
	('ramhorn', 'Ram Horn', 20, 1, 'item_standard', 1, 454, '{}', 'Can be sold or crafted'),
	('rams', 'Ram pelt', 20, 1, 'item_standard', 1, 455, '{}', 'Can be sold or crafted'),
	('Rams_Head', 'Rams Head', 10, 1, 'item_standard', 1, 241, '{}', 'Can be sold or crafted'),
	('Rams_Head_Seed', 'Rams Head Seed', 10, 1, 'item_standard', 1, 242, '{}', 'Used for farming'),
	('raspberryale', 'Raspberry Ale', 10, 1, 'item_standard', 1, 243, '{}', 'Enjoy'),
	('rat_c', 'Rat', 20, 1, 'item_standard', 1, 432, '{}', 'Can be sold or crafted'),
	('ravenc', 'Raven claws', 20, 1, 'item_standard', 1, 502, '{}', 'Can be sold or crafted'),
	('ravenf', 'Raven feather', 20, 1, 'item_standard', 1, 503, '{}', 'Can be sold or crafted'),
	('rectable', 'Rectangle Table', 20, 1, 'item_standard', 1, 751, '{}', 'Home furnishing'),
	('rectangle_table', 'Rectangle Table', 20, 1, 'item_standard', 1, 623, '{}', 'Home furnishing'),
	('Red_Raspberry', 'Red Raspberry', 10, 1, 'item_standard', 1, 244, '{}', 'Can be sold or crafted'),
	('Red_Raspberry_Seed', 'Red Raspberry Seed', 10, 1, 'item_standard', 1, 245, '{}', 'Used for farming'),
	('Red_Sage', 'Red Sage', 10, 1, 'item_standard', 1, 246, '{}', 'Can be sold or crafted'),
	('Red_Sage_Seed', 'Red Sage Seed', 10, 1, 'item_standard', 1, 247, '{}', 'Used for farming'),
	('repeaterbarrel', 'Repeater Barrel', 5, 1, 'item_standard', 1, 248, '{}', 'Gun part'),
	('repeatermold', 'Repeater Mold', 5, 1, 'item_standard', 1, 249, '{}', 'Gun part'),
	('repeaterreceiver', 'Repeater Receiver', 5, 1, 'item_standard', 1, 250, '{}', 'Gun part'),
	('repeaterrecmold', 'Repeater Receiver Mold', 5, 1, 'item_standard', 1, 251, '{}', 'Gun part'),
	('repeaterstock', 'Repeater Stock', 5, 1, 'item_standard', 1, 252, '{}', 'Gun part'),
	('revolverbarrel', 'Revolver Barrel', 5, 1, 'item_standard', 1, 253, '{}', 'Gun part'),
	('revolvercylinder', 'Revolver Cylinder', 5, 1, 'item_standard', 1, 254, '{}', 'Gun part'),
	('revolverhandle', 'Revolver Handle', 5, 1, 'item_standard', 1, 255, '{}', 'Gun part'),
	('revolvermold', 'Revolver Mold', 5, 1, 'item_standard', 1, 256, '{}', 'Gun part'),
	('riflebarrel', 'Rifle Barrel', 5, 1, 'item_standard', 1, 257, '{}', 'Gun part'),
	('riflemold', 'Rifle Mold', 5, 1, 'item_standard', 1, 258, '{}', 'Gun part'),
	('riflereceiver', 'Rifle Receiver', 5, 1, 'item_standard', 1, 259, '{}', 'Gun part'),
	('riflerecmold', 'Rifle Receiver Mold', 5, 1, 'item_standard', 1, 260, '{}', 'Gun part'),
	('riflestock', 'Rifle Stock', 5, 1, 'item_standard', 1, 261, '{}', 'Gun part'),
	('roach', 'Roach', 10, 1, 'item_standard', 0, 262, '{}', 'nice item'),
	('robberyplanning', 'Robbery Planning Set', 20, 1, 'item_standard', 1, 604, '{}', 'nice item'),
	('robin_c', 'Robin', 20, 1, 'item_standard', 1, 433, '{}', 'Can be sold'),
	('rock', 'Rock', 30, 1, 'item_standard', 0, 263, '{}', 'Can be sold or crafted'),
	('rollingpaper', 'Rolling paper', 30, 1, 'item_standard', 1, 264, '{}', 'Used for cigarettes'),
	('roundtable', 'Round Table', 20, 1, 'item_standard', 1, 749, '{}', 'Home furnishing'),
	('round_table', 'Round Table', 20, 1, 'item_standard', 1, 621, '{}', 'Home furnishing'),
	('rspoonb', 'Roseta Spoonbill beak', 20, 1, 'item_standard', 1, 497, '{}', 'Can be sold or crafted'),
	('rspoonf', 'Roseta Spoonbill feather', 20, 1, 'item_standard', 1, 496, '{}', 'Can be sold or crafted'),
	('rubber', 'Rubber', 20, 1, 'item_standard', 0, 265, '{}', 'Can be sold or crafted'),
	('rubbertube', 'Rubber Tube', 5, 1, 'item_standard', 0, 841, '{}', 'Can be sold or crafted'),
	('salamelle', 'Fresh Pork ', 20, 1, 'item_standard', 1, 266, '{}', 'Can be sold or crafted'),
	('salmon', 'Salmon', 10, 1, 'item_standard', 0, 267, '{}', 'Can be sold or crafted'),
	('salt', 'Salt', 20, 1, 'item_standard', 1, 268, '{}', 'Can be sold or crafted'),
	('Saltbush', 'Saltbush', 10, 1, 'item_standard', 1, 269, '{}', 'Can be sold or crafted'),
	('Saltbush_Seed', 'Saltbush Seed', 10, 1, 'item_standard', 1, 270, '{}', 'Used for farming'),
	('sap', 'Sap', 20, 1, 'item_standard', 0, 271, '{}', 'Can be sold or crafted'),
	('sarsaparilla', 'Sarsaparilla', 10, 1, 'item_standard', 1, 272, '{}', 'Nice day for one'),
	('scale', 'Scale', 5, 1, 'item_standard', 1, 273, '{}', 'nice item'),
	('scentg', 'Scent glad', 20, 1, 'item_standard', 1, 492, '{}', 'Can be sold or crafted'),
	('seagullb', 'Seagull beak', 20, 1, 'item_standard', 1, 495, '{}', 'Can be sold or crafted'),
	('seagullf', 'Seagull feather', 20, 1, 'item_standard', 1, 494, '{}', 'Can be sold or crafted'),
	('secondchance', 'Second Chance', 10, 1, 'item_standard', 1, 274, '{}', 'nice item'),
	('sheephead', 'Sheep head', 20, 1, 'item_standard', 1, 493, '{}', 'Can be sold or crafted'),
	('shellcasing', 'Shell Casing', 40, 1, 'item_standard', 1, 275, '{}', 'Gun part'),
	('shootingtarget', 'Shooting Target', 20, 1, 'item_standard', 1, 613, '{}', 'Home furnishing'),
	('shotgunbarrel', 'Shotgun Barrel', 5, 1, 'item_standard', 1, 276, '{}', 'Gun part'),
	('shotgunmold', 'Shotgun Mold', 5, 1, 'item_standard', 1, 277, '{}', 'Gun part'),
	('shotgunstock', 'Shotgun Stock', 5, 1, 'item_standard', 1, 278, '{}', 'Gun part'),
	('shrimps', 'Shrimp Stew', 1, 1, 'item_standard', 1, 279, '{}', 'Can be consumed'),
	('sidetable', 'side table 1', 20, 1, 'item_standard', 1, 782, '{}', 'Home furnishing'),
	('sidetablea', 'side table 2', 20, 1, 'item_standard', 1, 783, '{}', 'Home furnishing'),
	('sidetableb', 'side table 3', 20, 1, 'item_standard', 1, 784, '{}', 'Home furnishing'),
	('side_table', 'side table 1', 20, 1, 'item_standard', 1, 654, '{}', 'Home furnishing'),
	('side_tablea', 'side table 2', 20, 1, 'item_standard', 1, 655, '{}', 'Home furnishing'),
	('side_tableb', 'side table 3', 20, 1, 'item_standard', 1, 656, '{}', 'Home furnishing'),
	('singlebed', 'single bed', 20, 1, 'item_standard', 1, 666, '{}', 'Home furnishing'),
	('skullpost', 'Skull Post', 20, 1, 'item_standard', 1, 597, '{}', 'Home furnishing'),
	('skunks', 'Skunk Skin', 10, 1, 'item_standard', 1, 918, '{}', 'Can be sold or crafted'),
	('smallchest', 'Small Chest', 1, 1, 'item_standard', 1, 657, '{}', 'Home furnishing'),
	('smallmcandle', 'Small Melted Candle', 20, 1, 'item_standard', 1, 662, '{}', 'Home furnishing'),
	('Small_Leather', 'Small Leather', 10, 1, 'item_standard', 1, 280, '{}', 'Can be sold or crafted'),
	('SnakeSkin', 'Snake Skin', 20, 1, 'item_standard', 1, 281, '{}', 'Can be sold or crafted'),
	('snaket', 'Snake tooth', 20, 1, 'item_standard', 1, 490, '{}', 'Can be sold or crafted'),
	('Snake_Poison', 'Snake Poison', 10, 1, 'item_standard', 1, 282, '{}', 'Can be sold or crafted'),
	('soborno', 'Soborno Alcohol', 15, 1, 'item_standard', 0, 283, '{}', 'Can be consumed'),
	('songbird2_c', 'Scarlet songbird', 20, 1, 'item_standard', 1, 435, '{}', 'Can be sold'),
	('songbird_c', 'Songbird', 20, 1, 'item_standard', 1, 434, '{}', 'Can be sold'),
	('sparrow0_c', 'Common Sparrow', 20, 1, 'item_standard', 1, 436, '{}', 'Can be sold'),
	('sparrow1_c', 'Sparrow', 20, 1, 'item_standard', 1, 437, '{}', 'Can be sold'),
	('sparrow2_c', 'Golden Sparrow', 20, 1, 'item_standard', 1, 438, '{}', 'Can be sold'),
	('squirrel_black_c', 'Black Squirrel', 20, 1, 'item_standard', 1, 441, '{}', 'Can be sold or crafted'),
	('squirrel_grey_c', 'Gray Squirrel', 20, 1, 'item_standard', 1, 439, '{}', 'Can be sold or crafted'),
	('squirrel_red_c', 'Red Squirrel', 20, 1, 'item_standard', 1, 440, '{}', 'Can be sold or crafted'),
	('standard_table', 'Table', 20, 1, 'item_standard', 1, 622, '{}', 'Home furnishing'),
	('standingtorch', 'Stading Torch', 20, 1, 'item_standard', 1, 612, '{}', 'Home furnishing'),
	('steak', 'Steak', 10, 1, 'item_standard', 1, 284, '{}', 'Can be consumed'),
	('steakveg', 'Steak with Veggies', 10, 1, 'item_standard', 1, 285, '{}', 'Can be consumed'),
	('stillkit', 'Still Kit', 5, 1, 'item_standard', 1, 843, '{}', 'So...uh....what\'s going on?'),
	('stim', 'Horse Stimulant', 2, 1, 'item_standard', 1, 286, '{}', 'Horse go fast'),
	('stolenmerch', 'Stolen Items', 10, 1, 'item_standard', 0, 287, '{}', 'nice item'),
	('stone', 'Stone', 50, 1, 'item_standard', 0, 901, '{}', 'Can be sold or crafted'),
	('stonehammer', 'Stone Hammer', 5, 1, 'item_standard', 1, 288, '{}', 'nice item'),
	('stringy', 'Stringy meat', 20, 1, 'item_standard', 1, 574, '{}', 'Can be sold or crafted'),
	('sugar', 'Sugar', 20, 1, 'item_standard', 1, 289, '{}', 'Used for cooking'),
	('sugarcaneseed', 'Surgarcane seed', 10, 1, 'item_standard', 1, 290, '{}', 'Used for farming'),
	('sugarcube', 'Sugar Cube', 10, 1, 'item_standard', 1, 347, '{}', 'Horse treat'),
	('sulfur', 'Sulfur', 30, 1, 'item_standard', 0, 291, '{}', 'Can be sold or crafted'),
	('syn', 'Syn', 50, 1, 'item_standard', 1, 292, '{}', 'nice item'),
	('synpackage', 'Syn Package', 10, 1, 'item_standard', 1, 293, '{}', 'nice item'),
	('syringe', 'Syringe', 20, 1, 'item_standard', 1, 294, '{}', 'Administer meds'),
	('syringecert', 'Syringe Cert', 10, 1, 'item_standard', 1, 295, '{}', 'nice item'),
	('tent', 'Tent', 1, 1, 'item_standard', 1, 296, '{}', 'Home furnishing'),
	('tent2', 'Trader Tent', 20, 1, 'item_standard', 1, 588, '{}', 'Home furnishing'),
	('tent3', 'Simple Tent', 20, 1, 'item_standard', 1, 589, '{}', 'Home furnishing'),
	('tent4', 'Canvas Shade', 20, 1, 'item_standard', 1, 590, '{}', 'Home furnishing'),
	('tequila', 'Tequila', 10, 1, 'item_standard', 1, 297, '{}', 'Wait, it\'s tomorrow already'),
	('Texas_Bonnet', 'Texas Bonnet', 10, 1, 'item_standard', 1, 298, '{}', 'Can be sold or crafted'),
	('Texas_Bonnet_Seed', 'Texas Bonnet Seed', 10, 1, 'item_standard', 1, 299, '{}', 'Used for farming'),
	('timbertable', 'Timber Table', 20, 1, 'item_standard', 1, 752, '{}', 'Home furnishing'),
	('timber_table', 'Timber Table', 20, 1, 'item_standard', 1, 624, '{}', 'Home furnishing'),
	('tipi', 'Native Tipi', 20, 1, 'item_standard', 1, 596, '{}', 'home furnishing'),
	('toaddesert_c', 'Desert Toad', 20, 1, 'item_standard', 1, 444, '{}', 'Can be sold or crafted'),
	('toadpoison_c', 'Poisoned Toad', 20, 1, 'item_standard', 1, 443, '{}', 'Can be sold or crafted'),
	('toad_c', 'Toad', 20, 1, 'item_standard', 1, 442, '{}', 'Can be sold or crafted'),
	('token', 'Camp License', 5, 1, 'item_standard', 1, 300, '{}', 'To be kept in main storage'),
	('toolbarrel', 'Tool Barrel', 20, 1, 'item_standard', 1, 767, '{}', 'nice item'),
	('tool_barrel', 'Tool Barrel', 20, 1, 'item_standard', 1, 639, '{}', 'nice item'),
	('trainkey', 'Train Key', 1, 1, 'item_standard', 1, 301, '{}', 'nice item'),
	('trayoffood', 'Serving Table', 20, 1, 'item_standard', 1, 614, '{}', 'Home furnishing'),
	('tropicalPunchMash', 'Ginseng Mash', 10, 1, 'item_standard', 0, 302, '{}', 'Delicious'),
	('tropicalPunchMoonshine', 'Ginseng Moonshine', 10, 1, 'item_standard', 0, 303, '{}', 'Got a sweet tang....don\'t it'),
	('trout', 'Trout', 10, 1, 'item_standard', 0, 304, '{}', 'Can be sold or crafted'),
	('turkeyb', 'Turkey beak', 20, 1, 'item_standard', 1, 484, '{}', 'Can be sold or crafted'),
	('turkeyf', 'Turkey feather', 20, 1, 'item_standard', 1, 483, '{}', 'Can be sold or crafted'),
	('TurtleShell', 'Turtle Shell', 20, 1, 'item_standard', 1, 305, '{}', 'Can be sold or crafted'),
	('turtlet', 'Turtle tooth', 20, 1, 'item_standard', 1, 482, '{}', 'Can be sold or crafted'),
	('tylenol', 'Tylenol', 10, 1, 'item_standard', 1, 306, '{}', 'Pain be gone...for four hours'),
	('undertaker1', 'Coffin', 20, 1, 'item_standard', 1, 609, '{}', 'what you put in that?'),
	('undertaker2', 'Flower Coffin', 20, 1, 'item_standard', 1, 610, '{}', 'that\'s pretty...what\'s in it?'),
	('unique_brad_horsesugar', 'Brad Horse Sugar', 5, 1, 'item_standard', 1, 350, '{}', 'nice item'),
	('unique_horse_feed', 'Horse Feed', 5, 1, 'item_standard', 1, 349, '{}', 'Filling Horse Meal'),
	('venison', 'Venison', 20, 1, 'item_standard', 1, 566, '{}', 'Can be sold or crafted'),
	('Violet_Snowdrop', 'Violet Snowdrop', 10, 1, 'item_standard', 1, 308, '{}', 'Can be sold or crafted'),
	('Violet_Snowdrop_Seed', 'Violet Snowdrop Seed', 10, 1, 'item_standard', 1, 309, '{}', 'Used for farming'),
	('vodka', 'Vodka', 10, 1, 'item_standard', 1, 310, '{}', 'Didn\'t we have potatoes the other day?'),
	('vulturetaxi', 'Vulture Taxidermy', 20, 1, 'item_standard', 1, 772, '{}', 'nice item'),
	('Vulture_Egg', 'Vulture Egg', 10, 1, 'item_standard', 1, 311, '{}', 'Can be sold or crafted'),
	('vulture_taxidermy', 'Vulture Taxidermy', 20, 1, 'item_standard', 1, 644, '{}', 'nice item'),
	('washtub', 'Wash Tub', 20, 1, 'item_standard', 1, 637, '{}', 'Home furnishing'),
	('water', 'Water', 15, 1, 'item_standard', 1, 312, '{}', 'The essence of life'),
	('waterbarrel', 'Water Barrel', 20, 1, 'item_standard', 1, 587, '{}', 'nice item'),
	('wateringcan', 'Water Jug', 10, 1, 'item_standard', 1, 313, '{}', 'Used for farming'),
	('wateringcan_dirtywater', 'Dirty Watering Jug', 10, 1, 'item_standard', 1, 314, '{}', 'nice item'),
	('wateringcan_empty', 'Empty Watering Jug', 10, 1, 'item_standard', 1, 315, '{}', 'Used for Farming'),
	('waterpump', 'Water Pump', 20, 1, 'item_standard', 1, 755, '{}', 'Home furnishing'),
	('water_pump', 'Water Pump', 20, 1, 'item_standard', 1, 627, '{}', 'Home furnishing'),
	('whisky', 'Whisky', 10, 1, 'item_standard', 1, 316, '{}', 'This is water round these parts'),
	('wickerbench', 'Wicker Bench', 20, 1, 'item_standard', 1, 778, '{}', 'Home furnishing'),
	('wicker_bench', 'Wicker Bench', 20, 1, 'item_standard', 1, 650, '{}', 'Home furnishing'),
	('wildCiderMash', 'Black Berry Mash', 10, 1, 'item_standard', 0, 317, '{}', 'Used for crafting'),
	('wildCiderMoonshine', 'Black Berry Moonshine', 10, 1, 'item_standard', 0, 318, '{}', 'That\'s got some bite'),
	('Wild_Feverfew', 'Wild Feverfew', 10, 1, 'item_standard', 1, 321, '{}', 'Can be sold or crafted'),
	('Wild_Feverfew_Seed', 'Wild Feverfew Seed', 10, 1, 'item_standard', 1, 322, '{}', 'Used for farming'),
	('Wild_Mint', 'Wild Mint', 10, 1, 'item_standard', 1, 323, '{}', 'Can be sold or crafted'),
	('Wild_Mint_Seed', 'Wild Mint Seed', 10, 1, 'item_standard', 1, 324, '{}', 'Used for farming'),
	('Wild_Rhubarb', 'Wild Rhubarb', 10, 1, 'item_standard', 1, 325, '{}', 'Can be sold or crafted'),
	('Wild_Rhubarb_Seed', 'Wild Rhubarb Seed', 10, 1, 'item_standard', 1, 326, '{}', 'Used for farming'),
	('wine', 'Wine', 10, 1, 'item_standard', 1, 327, '{}', 'I ain\'t no pleb'),
	('Wintergreen_Berry', 'Wintergreen Berry', 10, 1, 'item_standard', 1, 328, '{}', 'Can be sold or crafted'),
	('Wintergreen_Berry_Seed', 'Wintergreen Berry Seed', 10, 1, 'item_standard', 1, 329, '{}', 'Used for farming'),
	('Wisteria', 'Wisteria', 10, 1, 'item_standard', 1, 330, '{}', 'Can be sold or crafted'),
	('Wisteria_Seed', 'Wisteria Seed', 10, 1, 'item_standard', 1, 331, '{}', 'Used for farming'),
	('wojape', 'Wojape', 5, 1, 'item_standard', 1, 332, '{}', 'nice item'),
	('wolfheart', 'Wolf heart', 20, 1, 'item_standard', 1, 476, '{}', 'Can be sold or crafted'),
	('wolfpelt', 'Wolf skin', 20, 1, 'item_standard', 1, 477, '{}', 'Can be sold or crafted'),
	('wolftooth', 'Wolf tooth', 20, 1, 'item_standard', 1, 478, '{}', 'Can be sold or crafted'),
	('wood', 'Soft Wood', 20, 1, 'item_standard', 0, 333, '{}', 'Can be sold or crafted'),
	('woodbench', 'Wooden Bench', 20, 1, 'item_standard', 1, 777, '{}', 'Home furnishing'),
	('woodchair', 'Wood Chair', 20, 1, 'item_standard', 1, 747, '{}', 'Home furnishing'),
	('wooden_bench', 'Wooden Bench', 20, 1, 'item_standard', 1, 649, '{}', 'Home furnishing'),
	('wooden_boards', 'Wooden Boards', 25, 1, 'item_standard', 0, 334, '{}', 'Used for crafting'),
	('woodpeck01_c', 'Woodpecker', 20, 1, 'item_standard', 1, 445, '{}', 'Can be sold'),
	('woodpeck02_c', 'Woodpecker 2', 20, 1, 'item_standard', 1, 446, '{}', 'Can be sold'),
	('wood_chair', 'Wood Chair', 20, 1, 'item_standard', 1, 619, '{}', 'Home furnsihing'),
	('wool', 'Wool', 50, 1, 'item_standard', 1, 335, '{}', 'Can be sold or crafted'),
	('wsnakes', 'Western rattlesnake pelt', 20, 1, 'item_standard', 1, 489, '{}', 'Can be sold or crafted'),
	('wsnakeskin', 'Watersnake pelt', 20, 1, 'item_standard', 1, 485, '{}', 'Can be sold or crafted'),
	('Yarrow', 'Yarrow', 10, 1, 'item_standard', 1, 336, '{}', 'Can be sold or crafted'),
	('Yarrow_Seed', 'Yarrow Seed', 10, 1, 'item_standard', 1, 337, '{}', 'Used for farming');

-- Dumping structure for table vorpcore_1.items_crafted
CREATE TABLE IF NOT EXISTS `items_crafted` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `character_id` int(11) NOT NULL,
  `item_id` int(11) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`metadata`)),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID` (`id`),
  KEY `crafted_item_idx` (`character_id`)
) ENGINE=InnoDB AUTO_INCREMENT=631 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping structure for table vorpcore_1.jail
CREATE TABLE IF NOT EXISTS `jail` (
  `identifier` varchar(100) NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL DEFAULT '0',
  `characterid` varchar(5) NOT NULL DEFAULT '0',
  `time` varchar(100) NOT NULL DEFAULT '0',
  `time_s` varchar(100) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table vorpcore_1.jail: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.jobmanager
CREATE TABLE IF NOT EXISTS `jobmanager` (
  `identifier` varchar(50) NOT NULL,
  `charidentifier` int(11) NOT NULL,
  `jobname` varchar(50) NOT NULL,
  PRIMARY KEY (`identifier`,`charidentifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping structure for table vorpcore_1.loadout
CREATE TABLE IF NOT EXISTS `loadout` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(50) NOT NULL,
  `charidentifier` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `ammo` varchar(255) NOT NULL DEFAULT '{}',
  `components` varchar(255) NOT NULL DEFAULT '{}',
  `dirtlevel` double DEFAULT 0,
  `mudlevel` double DEFAULT 0,
  `conditionlevel` double DEFAULT 0,
  `rustlevel` double DEFAULT 0,
  `used` tinyint(4) DEFAULT 0,
  `used2` tinyint(4) DEFAULT 0,
  `dropped` int(11) NOT NULL DEFAULT 0,
  `comps` longtext NOT NULL DEFAULT '{}',
  `label` varchar(50) DEFAULT NULL,
  `curr_inv` varchar(100) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping structure for table vorpcore_1.mailbox_mails
CREATE TABLE IF NOT EXISTS `mailbox_mails` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sender_id` varchar(50) DEFAULT NULL,
  `sender_firstname` varchar(50) DEFAULT NULL,
  `sender_lastname` varchar(50) DEFAULT NULL,
  `receiver_id` varchar(50) DEFAULT NULL,
  `receiver_firstname` varchar(50) DEFAULT NULL,
  `receiver_lastname` varchar(50) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `opened` tinyint(1) DEFAULT 0,
  `received_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping structure for table vorpcore_1.outfits
CREATE TABLE IF NOT EXISTS `outfits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(45) NOT NULL,
  `charidentifier` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `comps` longtext DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping structure for table vorpcore_1.real_logic_horses
CREATE TABLE IF NOT EXISTS `real_logic_horses` (
  `update_time` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- Dumping data for table vorpcore_1.real_logic_horses: ~0 rows (approximately)
INSERT INTO `real_logic_horses` (`update_time`) VALUES
	(7);

-- Dumping structure for table vorpcore_1.rooms
CREATE TABLE IF NOT EXISTS `rooms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `interiorId` int(11) NOT NULL,
  `inventory` longtext DEFAULT NULL,
  `identifier` varchar(60) NOT NULL,
  `charidentifier` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table vorpcore_1.rooms: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.scenes
CREATE TABLE IF NOT EXISTS `scenes` (
  `autoid` int(20) NOT NULL AUTO_INCREMENT,
  `id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `charid` int(30) NOT NULL DEFAULT 0,
  `text` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `coords` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`coords`)),
  `font` int(30) NOT NULL DEFAULT 0,
  `color` int(30) NOT NULL DEFAULT 0,
  `bg` int(30) NOT NULL DEFAULT 0,
  `scale` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`autoid`),
  KEY `autoid` (`autoid`),
  KEY `id` (`id`),
  KEY `charid` (`charid`),
  CONSTRAINT `FK_bccscenes_users` FOREIGN KEY (`id`) REFERENCES `users` (`identifier`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping structure for table vorpcore_1.society_ledger
CREATE TABLE IF NOT EXISTS `society_ledger` (
  `job` longtext DEFAULT NULL,
  `ledger` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping structure for table vorpcore_1.stables
CREATE TABLE IF NOT EXISTS `stables` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(50) NOT NULL,
  `charidentifier` int(11) NOT NULL,
  `name` varchar(30) NOT NULL,
  `modelname` varchar(70) NOT NULL,
  `type` varchar(11) NOT NULL,
  `status` longtext DEFAULT NULL,
  `xp` int(11) DEFAULT 0,
  `injured` int(11) DEFAULT 0,
  `gear` longtext DEFAULT NULL,
  `isDefault` int(11) NOT NULL DEFAULT 0,
  `inventory` longtext DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping structure for table vorpcore_1.users
CREATE TABLE IF NOT EXISTS `users` (
  `identifier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `group` varchar(50) DEFAULT 'user',
  `warnings` int(11) DEFAULT 0,
  `banned` tinyint(1) DEFAULT NULL,
  `banneduntil` int(10) DEFAULT 0,
  `char` varchar(50) NOT NULL DEFAULT 'false',
  PRIMARY KEY (`identifier`),
  UNIQUE KEY `identifier` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping structure for table vorpcore_1.wagons
CREATE TABLE IF NOT EXISTS `wagons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(40) NOT NULL,
  `charid` int(11) NOT NULL,
  `selected` int(11) NOT NULL DEFAULT 0,
  `model` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `items` longtext NOT NULL DEFAULT '{}',
  `weapons` longtext NOT NULL DEFAULT '{}',
  `comp_extras` varchar(500) DEFAULT '{"1":"1","10":"1","20":"1","8":"1","6":"1","11":"1","7":"1","15":"1","18":"1","19":"1","16":"1","17":"1","3":"1","2":"1","5":"1","4":"1","13":"1","12":"1","9":"1","14":"1"}',
  `comp_lantern` varchar(255) DEFAULT 'none',
  `comp_liveries` varchar(255) DEFAULT '-1',
  `comp_tints` varchar(255) DEFAULT '-1',
  `addon_ability` bigint(20) DEFAULT 0,
  `damage_wheel` int(11) NOT NULL DEFAULT 0,
  `health_cart` int(11) NOT NULL DEFAULT 1000,
  `animals` longtext NOT NULL DEFAULT '{}',
  `addonArray` longtext NOT NULL DEFAULT '{}',
  `cityPosition` int(11) NOT NULL DEFAULT 0,
  `spotPosition` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `FK_horses_characters` (`charid`),
  KEY `model` (`model`)
) ENGINE=InnoDB AUTO_INCREMENT=914 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- Dumping structure for table vorpcore_1.wagon_water
CREATE TABLE IF NOT EXISTS `wagon_water` (
  `identifier` varchar(255) DEFAULT '0',
  `charid` varchar(255) DEFAULT '0',
  `wagon` varchar(255) DEFAULT '0',
  `water` varchar(255) DEFAULT '0',
  `wagon_name` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

-- Dumping data for table vorpcore_1.wagon_water: ~0 rows (approximately)

-- Dumping structure for table vorpcore_1.whitelist
CREATE TABLE IF NOT EXISTS `whitelist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `status` tinyint(1) DEFAULT NULL,
  `firstconnection` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `identifier` (`identifier`) USING BTREE,
  CONSTRAINT `FK_characters_whitelist` FOREIGN KEY (`identifier`) REFERENCES `users` (`identifier`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
